id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Close stale issues and pull requests
      frequencies:
      - hourly:
          hour: 12
      filters:
      - isOpen
      - hasLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      - hasLabel:
          label: ':zzz: no-recent-activity'
      - noActivitySince:
          days: 7
      actions:
      - closeIssue
      - removeMilestone
    - description: Add no recent activity label to issues and pull requests
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isOpen
      - hasLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      - noActivitySince:
          days: 14
      - isNotLabeledWith:
          label: ':zzz: no-recent-activity'
      actions:
      - addLabel:
          label: ':zzz: no-recent-activity'
      - addReply:
          reply: >-
            This submission has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **14 days**. 


            It will be closed if no further activity occurs **within 7 days of this comment**.
    - description: Add draft label
      frequencies:
      - hourly:
          hour: 4
      filters:
      - isDraftPullRequest
      actions:
      - addLabel:
          label: draft
    - description: Remove draft label
      frequencies:
      - hourly:
          hour: 4
      filters:
      - isNotDraftPullRequest
      actions:
      - removeLabel:
          label: draft
    - description: Close OLD draft PRs
      frequencies:
      - hourly:
          hour: 12
      filters:
      - isDraftPullRequest
      - created:
          before: 180
      - isOpen
      - noActivitySince:
          days: 180
      actions:
      - closeIssue
      - addReply:
          reply: The current status of this "draft" PR has persisted for over 180 days, making it highly probable that it is no longer aligned with the latest codebase. Our repository is set up to automatically close draft PRs that have become outdated, and it requests the author to revisit and reopen them if they deem it necessary, thereby bringing them to the team's attention.
      - addLabel:
          label: draft
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      then:
      - addCodeFlowLink
      description: Add a CodeFlow link to new pull requests
    - if:
      - payloadType: Pull_Request_Review
      - isAction:
          action: Submitted
      - isReviewState:
          reviewState: Changes_requested
      then:
      - addLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      description: Add needs author feedback label to pull requests when changes are requested
    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          issueAuthor: True
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      then:
      - removeLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      description: Remove needs author feedback label when the author responds to a pull request
    - if:
      - payloadType: Issue_Comment
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      then:
      - removeLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      description: Remove needs author feedback label when the author comments on a pull request
    - if:
      - payloadType: Pull_Request_Review
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      then:
      - removeLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      description: Remove needs author feedback label when the author responds to a pull request review comment
    - if:
      - payloadType: Pull_Request
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: ':zzz: no-recent-activity'
      then:
      - removeLabel:
          label: ':zzz: no-recent-activity'
      description: Remove no recent activity label from pull requests
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: ':zzz: no-recent-activity'
      then:
      - removeLabel:
          label: ':zzz: no-recent-activity'
      description: Remove no recent activity label when a pull request is commented on
    - if:
      - payloadType: Pull_Request_Review
      - hasLabel:
          label: ':zzz: no-recent-activity'
      then:
      - removeLabel:
          label: ':zzz: no-recent-activity'
      description: Remove no recent activity label when a pull request is reviewed
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: ':octocat:  automerge'
      then:
      - enableAutoMerge:
          mergeMethod: Squash
      description: Automatically merge pull requests
    - if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: ':octocat:  automerge'
      then:
      - disableAutoMerge
      description: Automatically merge pull requests
    - if:
      - payloadType: Pull_Request
      then:
      - inPrLabel:
          label: ':construction: work in progress'
      description: In-PR label
    - if:
      - payloadType: Pull_Request
      - targetsBranch:
          branch: main
      - and:
        - isAction:
            action: Closed
        - isMerged
        - not:
            titleContains:
              pattern: '[main] Update dependencies'
              isRegex: False
      then:
      - addMilestone:
          milestone: 9.0 Preview5
      description: Apply milestone to PRs on the main branch
      triggerOnOwnActions: true
    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          user: dotnet-maestro[bot]
          issueAuthor: False
      - isAction:
          action: Opened
      then:
      - approvePullRequest:
          comment: Go, you big red fire engine!
      description: Auto-approve maestro PRs
    - if:
      - payloadType: Pull_Request
      - labelAdded:
          label: ':octocat:  automerge'
      - or:
        - activitySenderHasPermission:
            permission: Admin
        - activitySenderHasPermission:
            permission: Write
      then:
      - approvePullRequest:
          comment: Happy to oblige
      description: Auto-approve auto-merge PRs
    - if:
      - payloadType: Issue_Comment
      then:
      - cleanEmailReply
      description: Cleanse emails
    - if:
      - payloadType: Pull_Request
      then:
      - assignTo:
          author: True
      description: Assign PRs to authors
    - if:
      - payloadType: Issue_Comment
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      then:
      - removeLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      description: Remove needs author feedback label when the author comments on an issue
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: ':zzz: no-recent-activity'
      then:
      - removeLabel:
          label: ':zzz: no-recent-activity'
      description: Remove no recent activity label when an issue is commented on
    - if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: ':zzz: no-recent-activity'
      then:
      - removeLabel:
          label: ':zzz: no-recent-activity'
      description: Remove no recent activity label from issue
    - if:
      - payloadType: Pull_Request
      - isAssignedToUser:
          user: dotnet-bot
      - titleContains:
          pattern: OneLocBuild
          isRegex: False
      - isAction:
          action: Opened
      then:
      - approvePullRequest:
          comment: Go, you big red fire engine!
      - addLabel:
          label: ':octocat:  automerge'
      description: Auto-approve OneLocBuild PRs
      triggerOnOwnActions: true
    - if:
      - payloadType: Pull_Request
      - titleContains:
          pattern: Enable nullability
          isRegex: False
      then:
      - addLabel:
          label: 'area: NRT'
      description: 'Apply "area: NRT" label'
    - if:
      - payloadType: Issues
      - isOpen
      - labelAdded:
          label: help wanted
      then:
      - addMilestone:
          milestone: Help wanted
      - addReply:
          reply: >-
            This issue is now marked as "help wanted", and we’re looking for a community volunteer to work on this issue. If we receive no interest in 180 days, we will close the issue. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/winforms/issue-lifecycle).


            Happy Coding!
      description: 'help wanted: labelled'
    - if:
      - payloadType: Pull_Request
      - isAction: Closed
      then:
      - removeLabel:
          label: ':construction: work in progress'
      - removeLabel:
          label: ':mailbox_with_mail: waiting-for-testing'
      - removeLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      - removeLabel:
          label: ready-to-merge
      - removeLabel:
          label: waiting-on-team
      - removeLabel:
          label: waiting-review
      description: Remove invalid labels after PR is merged.
    - if:
      - payloadType: Issues
      - or:
        - isAction:
            action: Closed
      then:
      - removeLabel:
          label: untriaged
      - removeLabel:
          label: ':mailbox_with_no_mail: waiting-author-feedback'
      - removeLabel:
          label: ':mailbox_with_mail: waiting-for-testing'
      description: Remove intermediate labels from closed issue.
onFailure: 
onSuccess:
