// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// This file is used by Code Analysis to maintain SuppressMessage

[assembly: SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "Public API", Scope = "type", Target = "~T:System.Windows.Forms.Design.ThemedScrollbarWindow")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.ComponentModel.Design.ByteViewer.OnLayout(System.Windows.Forms.LayoutEventArgs)")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.ComponentModel.Design.CollectionEditor.CollectionForm.GetService(System.Type)~System.Object")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformFlush(System.ComponentModel.Design.Serialization.IDesignerSerializationManager)")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(System.ComponentModel.Design.Serialization.IDesignerSerializationManager)")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.Windows.Forms.Design.ComponentTray.GetService(System.Type)~System.Object")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.Windows.Forms.Design.ComponentTray.OnDragDrop(System.Windows.Forms.DragEventArgs)")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.Windows.Forms.Design.ComponentTray.OnDragEnter(System.Windows.Forms.DragEventArgs)")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.Windows.Forms.Design.ComponentTray.OnDragOver(System.Windows.Forms.DragEventArgs)")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.Windows.Forms.Design.ComponentTray.OnGiveFeedback(System.Windows.Forms.GiveFeedbackEventArgs)")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.Windows.Forms.Design.ComponentTray.OnPaint(System.Windows.Forms.PaintEventArgs)")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.Windows.Forms.Design.MaskDescriptor.Equals(System.Object)~System.Boolean")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.Windows.Forms.Design.ScrollableControlDesigner.GetHitTest(System.Drawing.Point)~System.Boolean")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.EditorPropertyLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionPropertyItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.HeaderLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionTextItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.TextBoxPropertyLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionPropertyItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.TextLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionTextItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.CheckBoxPropertyLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionPropertyItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.MethodLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionMethodItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "False positive", Scope = "member", Target = "~P:System.Windows.Forms.Design.ControlDesigner.DesignerTarget")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Stream for testing", Scope = "member", Target = "~M:System.Windows.Forms.Design.ImageListImageEditor.LoadImageFromStream(System.IO.Stream,System.Boolean)~System.Windows.Forms.Design.ImageListImage")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Public API", Scope = "member", Target = "~F:System.Windows.Forms.Design.ControlDesigner.InvalidPoint")]
