// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// This file is used by Code Analysis to maintain SuppressMessage

[assembly: SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "Public API", Scope = "type", Target = "~T:System.Windows.Forms.Design.ThemedScrollbarWindow")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.EditorPropertyLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionPropertyItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.HeaderLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionTextItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.TextBoxPropertyLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionPropertyItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.TextLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionTextItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.CheckBoxPropertyLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionPropertyItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Visibility", Scope = "member", Target = "~M:System.ComponentModel.Design.DesignerActionPanel.MethodLine.CreateLineInfo(System.ComponentModel.Design.DesignerActionList,System.ComponentModel.Design.DesignerActionMethodItem)~System.ComponentModel.Design.DesignerActionPanel.StandardLineInfo")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "False positive", Scope = "member", Target = "~P:System.Windows.Forms.Design.ControlDesigner.DesignerTarget")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "Stream for testing", Scope = "member", Target = "~M:System.Windows.Forms.Design.ImageListImageEditor.LoadImageFromStream(System.IO.Stream,System.Boolean)~System.Windows.Forms.Design.ImageListImage")]
