# This is a simple wrapper for eng/ci.yml so we have a place to define variables,
# since yaml doesn't have good support for delayed variable expansion
variables:
  Build.Repository.Clean: true
  _HelixType: build/product
  _HelixSource: pr/dotnet/winforms/$(Build.SourceBranch)
  _PublishType: none
  _SignType: test
  _DotNetPublishToBlobFeed: false

  # Change some values for internal builds
  ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.DefinitionName'], 'github'))) }}:
    _TeamName: DotNetCore
    _HelixSource: official/dotnet/winforms/$(Build.SourceBranch)
    _PublishType: blob
    _SignType: real
    _DotNetPublishToBlobFeed: true

# only trigger ci builds for the master branch
trigger:
- master

# To be added in the future when VSTS supports this feature
# only trigger pull request builds for the master branch
# pr:
# - master

# Call the ci.yml template, which does the real work
phases:
- template: /eng/ci.yml
  parameters:
    # Workaround for agent pool not able to be read from a runtime variable (move this up to user defined variables once the AzDO team fixes this)
    # runAsPublic is used in template expansion, so it can't be in a user defined variable
    # TODO: REMOVE THE BUILD.DEFINITIONNAME CHECK ONCE THE GITHUB REPO GOES PUBLIC
    ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.DefinitionName'], 'github'))) }}:
      agentPool: dotnet-internal-temp
      runAsPublic: false