# This is a simple wrapper for eng/ci.yml so we have a place to define variables,
# since yaml doesn't have good support for delayed variable expansion
variables:
  Build.Repository.Clean: true
  _HelixType: build/product
  
  # Change some variables based on build conditions
  ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest'), contains(variables['Build.DefinitionName'], 'github')) }}:
    _AgentPool : dotnet-internal-temp # todo: once github repo goes public, change this to dotnet-external-temp
    _RunAsPublic: true
    _HelixSource: pr/dotnet/winforms/$(Build.SourceBranch)
    _PublishType: none
    _SignType: test
    _DotNetPublishToBlobFeed : false
  # else
  ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.DefinitionName'], 'github'))) }}:
    _AgentPool : dotnet-internal-temp
    _RunAsPublic: false
    _TeamName: DotNetCore
    _HelixSource: official/dotnet/winforms/$(Build.SourceBranch)
    _PublishType: blob
    _SignType: real
    _DotNetPublishToBlobFeed : true

# only trigger builds for the master branch
trigger:
- master

# To be added in the future when VSTS supports this feature
# pr:
# - master

# call the ci.yml template, which does the real work
phases:
- template: /eng/ci.yml
  parameters:
    # agent pool is a special case, it needs to be constant when it's referenced (it can be a parameter)
    # The Azure DevOps team said this will be fixed in a future release
    #${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest'), contains(variables['Build.DefinitionName'], 'github')) }}:
      # todo: once github repo goes public, change this to dotnet-external-temp
    agentPool: ${{ variables['_AgentPool'] }}
    #${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.DefinitionName'], 'github'))) }}:
    #  agentPool: dotnet-internal-temp