# This is a simple wrapper for eng/ci.yml to get around the limitation of
# user-defined variables not being available in yaml expressions.

# Template parameters ARE available in yaml expressions, and parameters can have default values,
# so they can be used to control yaml flow.

variables:

  # clean the local repo on the build agents
  Build.Repository.Clean: true
  
# only trigger ci builds for the master branch
trigger:
- master

# To be added in the future when VSTS supports this feature
# only trigger pull request builds for the master branch
# pr:
# - master

# Call the ci.yml template, which does the real work
phases:
- template: /eng/ci.yml
  parameters:
    # TODO: REMOVE THE BUILD.DEFINITIONNAME CHECK ONCE THE GITHUB REPO GOES PUBLIC
    ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.DefinitionName'], 'github'))) }}:
      # agent pool can't be read from a user-defined variable (Azure DevOps limitation)
      agentPool: dotnet-internal-temp
      # runAsPublic is used in expressions, which can't read from user-defined variables
      runAsPublic: false