# This is a simple wrapper for eng/ci.yml so we have a place to define variables,
# since yaml doesn't have good support for delayed variable expansion
variables:
  Build.Repository.Clean: true
  _HelixType: build/product
  
  # Change some variables based on build conditions
  ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest'), contains(variables['Build.DefinitionName'], 'github')) }}:
    _RunAsPublic: true
    _AgentPool: dotnet-internal-temp # todo: once github repo goes public, change this to dotnet-external-temp
    _HelixSource: pr/dotnet/winforms/$(Build.SourceBranch)
    _PublishType: none
    _SignType: test
    _DotNetPublishToBlobFeed : false
  
  ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.DefinitionName'], 'github'))) }}:
    _RunAsPublic: false
    _AgentPool: dotnet-internal-temp
    _TeamName: DotNetCore
    _HelixSource: official/dotnet/winforms/$(Build.SourceBranch)
    _PublishType: blob
    _SignType: real
    _DotNetPublishToBlobFeed : true

# only trigger builds for the master branch
trigger:
- master

# To be added in the future when VSTS supports this feature
# pr:
# - master

# call the ci.yml template, which does the real work
phases:
- template: /eng/ci.yml
  parameters:
    runAsPublic: $(_RunAsPublic)
    agentPool: variables['_AgentPool']