//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms.Design.Editors.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Forms.Design.Editors.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Editor.
        /// </summary>
        public static string AnchorEditorAccName {
            get {
                return ResourceManager.GetString("AnchorEditorAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string AnchorEditorBottomAccName {
            get {
                return ResourceManager.GetString("AnchorEditorBottomAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string AnchorEditorLeftAccName {
            get {
                return ResourceManager.GetString("AnchorEditorLeftAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string AnchorEditorRightAccName {
            get {
                return ResourceManager.GetString("AnchorEditorRightAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string AnchorEditorTopAccName {
            get {
                return ResourceManager.GetString("AnchorEditorTopAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custo&amp;m format.
        /// </summary>
        public static string BindingFormattingDialogCustomFormat {
            get {
                return ResourceManager.GetString("BindingFormattingDialogCustomFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom format.
        /// </summary>
        public static string BindingFormattingDialogCustomFormatAccessibleDescription {
            get {
                return ResourceManager.GetString("BindingFormattingDialogCustomFormatAccessibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decimal places.
        /// </summary>
        public static string BindingFormattingDialogDecimalPlaces {
            get {
                return ResourceManager.GetString("BindingFormattingDialogDecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string BindingFormattingDialogFormatTypeCurrency {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the format for monetary values..
        /// </summary>
        public static string BindingFormattingDialogFormatTypeCurrencyExplanation {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeCurrencyExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string BindingFormattingDialogFormatTypeCustom {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a custom format string. A custom string may require extra handling unless it is a read-only value..
        /// </summary>
        public static string BindingFormattingDialogFormatTypeCustomExplanation {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeCustomExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        public static string BindingFormattingDialogFormatTypeCustomInvalidFormat {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeCustomInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        public static string BindingFormattingDialogFormatTypeDateTime {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the format for date and time values..
        /// </summary>
        public static string BindingFormattingDialogFormatTypeDateTimeExplanation {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeDateTimeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Formatting.
        /// </summary>
        public static string BindingFormattingDialogFormatTypeNoFormatting {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeNoFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use no formatting to display the value from the source without adornment..
        /// </summary>
        public static string BindingFormattingDialogFormatTypeNoFormattingExplanation {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeNoFormattingExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        public static string BindingFormattingDialogFormatTypeNumeric {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the format for numbers. Note that the Currency format type offers specialized formatting for monetary values..
        /// </summary>
        public static string BindingFormattingDialogFormatTypeNumericExplanation {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeNumericExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific.
        /// </summary>
        public static string BindingFormattingDialogFormatTypeScientific {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeScientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the format for values that use scientific notation..
        /// </summary>
        public static string BindingFormattingDialogFormatTypeScientificExplanation {
            get {
                return ResourceManager.GetString("BindingFormattingDialogFormatTypeScientificExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Null value:.
        /// </summary>
        public static string BindingFormattingDialogNullValue {
            get {
                return ResourceManager.GetString("BindingFormattingDialogNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Type.
        /// </summary>
        public static string BindingFormattingDialogType {
            get {
                return ResourceManager.GetString("BindingFormattingDialogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap files.
        /// </summary>
        public static string bitmapFileDescription {
            get {
                return ResourceManager.GetString("bitmapFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Preview.
        /// </summary>
        public static string CellStyleBuilderNormalPreviewAccName {
            get {
                return ResourceManager.GetString("CellStyleBuilderNormalPreviewAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Preview.
        /// </summary>
        public static string CellStyleBuilderSelectedPreviewAccName {
            get {
                return ResourceManager.GetString("CellStyleBuilderSelectedPreviewAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item &apos;{0}&apos; cannot be removed..
        /// </summary>
        public static string CollectionEditorCantRemoveItem {
            get {
                return ResourceManager.GetString("CollectionEditorCantRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Collection Editor.
        /// </summary>
        public static string CollectionEditorCaption {
            get {
                return ResourceManager.GetString("CollectionEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only component(s) selected..
        /// </summary>
        public static string CollectionEditorInheritedReadOnlySelection {
            get {
                return ResourceManager.GetString("CollectionEditorInheritedReadOnlySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &amp;properties:.
        /// </summary>
        public static string CollectionEditorProperties {
            get {
                return ResourceManager.GetString("CollectionEditorProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Select &amp;Properties:.
        /// </summary>
        public static string CollectionEditorPropertiesMultiSelect {
            get {
                return ResourceManager.GetString("CollectionEditorPropertiesMultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Properties:.
        /// </summary>
        public static string CollectionEditorPropertiesNone {
            get {
                return ResourceManager.GetString("CollectionEditorPropertiesNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove {0} objects.
        /// </summary>
        public static string CollectionEditorUndoBatchDesc {
            get {
                return ResourceManager.GetString("CollectionEditorUndoBatchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picker.
        /// </summary>
        public static string ColorEditorAccName {
            get {
                return ResourceManager.GetString("ColorEditorAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string ColorEditorPaletteTab {
            get {
                return ResourceManager.GetString("ColorEditorPaletteTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string ColorEditorStandardTab {
            get {
                return ResourceManager.GetString("ColorEditorStandardTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string ColorEditorSystemTab {
            get {
                return ResourceManager.GetString("ColorEditorSystemTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment Picker.
        /// </summary>
        public static string ContentAlignmentEditorAccName {
            get {
                return ResourceManager.GetString("ContentAlignmentEditorAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Middle.
        /// </summary>
        public static string ContentAlignmentEditorBottomCenterAccName {
            get {
                return ResourceManager.GetString("ContentAlignmentEditorBottomCenterAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        public static string ContentAlignmentEditorBottomLeftAccName {
            get {
                return ResourceManager.GetString("ContentAlignmentEditorBottomLeftAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        public static string ContentAlignmentEditorBottomRightAccName {
            get {
                return ResourceManager.GetString("ContentAlignmentEditorBottomRightAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Center.
        /// </summary>
        public static string ContentAlignmentEditorMiddleCenterAccName {
            get {
                return ResourceManager.GetString("ContentAlignmentEditorMiddleCenterAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Left.
        /// </summary>
        public static string ContentAlignmentEditorMiddleLeftAccName {
            get {
                return ResourceManager.GetString("ContentAlignmentEditorMiddleLeftAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Right.
        /// </summary>
        public static string ContentAlignmentEditorMiddleRightAccName {
            get {
                return ResourceManager.GetString("ContentAlignmentEditorMiddleRightAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        public static string ContentAlignmentEditorTopCenterAccName {
            get {
                return ResourceManager.GetString("ContentAlignmentEditorTopCenterAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        public static string ContentAlignmentEditorTopLeftAccName {
            get {
                return ResourceManager.GetString("ContentAlignmentEditorTopLeftAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        public static string ContentAlignmentEditorTopRightAccName {
            get {
                return ResourceManager.GetString("ContentAlignmentEditorTopRightAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DataGridView_Cancel {
            get {
                return ResourceManager.GetString("DataGridView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DataGridView_OK {
            get {
                return ResourceManager.GetString("DataGridView_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items collection cannot be modified when the DataSource property is set..
        /// </summary>
        public static string DataSourceLocksItems {
            get {
                return ResourceManager.GetString("DataSourceLocksItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Picker.
        /// </summary>
        public static string DockEditorAccName {
            get {
                return ResourceManager.GetString("DockEditorAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string DockEditorBottomAccName {
            get {
                return ResourceManager.GetString("DockEditorBottomAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string DockEditorFillAccName {
            get {
                return ResourceManager.GetString("DockEditorFillAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string DockEditorLeftAccName {
            get {
                return ResourceManager.GetString("DockEditorLeftAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string DockEditorNoneAccName {
            get {
                return ResourceManager.GetString("DockEditorNoneAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string DockEditorRightAccName {
            get {
                return ResourceManager.GetString("DockEditorRightAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string DockEditorTopAccName {
            get {
                return ResourceManager.GetString("DockEditorTopAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format String Dialog.
        /// </summary>
        public static string FormatStringDialogTitle {
            get {
                return ResourceManager.GetString("FormatStringDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files(*.*)|*.*.
        /// </summary>
        public static string GenericFileFilter {
            get {
                return ResourceManager.GetString("GenericFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string GenericOpenFile {
            get {
                return ResourceManager.GetString("GenericOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Help Files(*.chm,*.col,*.htm,*.html)|*.chm;*.col;*.htm;*.html|Compressed HTML Files(*.chm)|*.chm|Help Collection Files(*.col)|*.col|HTML Files(*.htm,*.html)|*.htm;*.html|All Files(*.*)|*.*.
        /// </summary>
        public static string HelpProviderEditorFilter {
            get {
                return ResourceManager.GetString("HelpProviderEditorFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Help File.
        /// </summary>
        public static string HelpProviderEditorTitle {
            get {
                return ResourceManager.GetString("HelpProviderEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon files.
        /// </summary>
        public static string iconFileDescription {
            get {
                return ResourceManager.GetString("iconFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images Collection Editor.
        /// </summary>
        public static string ImageCollectionEditorFormText {
            get {
                return ResourceManager.GetString("ImageCollectionEditorFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All image files.
        /// </summary>
        public static string imageFileDescription {
            get {
                return ResourceManager.GetString("imageFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LinkAreaEditorCancel {
            get {
                return ResourceManager.GetString("LinkAreaEditorCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkArea Editor.
        /// </summary>
        public static string LinkAreaEditorCaption {
            get {
                return ResourceManager.GetString("LinkAreaEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &amp;range of text to make your link:.
        /// </summary>
        public static string LinkAreaEditorDescription {
            get {
                return ResourceManager.GetString("LinkAreaEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LinkAreaEditorOK {
            get {
                return ResourceManager.GetString("LinkAreaEditorOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListViewSubItem.
        /// </summary>
        public static string ListViewSubItemBaseName {
            get {
                return ResourceManager.GetString("ListViewSubItemBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metafiles.
        /// </summary>
        public static string metafileFileDescription {
            get {
                return ResourceManager.GetString("metafileFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to begin a new line.
        ///Press Ctrl+Enter to accept Text..
        /// </summary>
        public static string MultilineStringEditorWatermark {
            get {
                return ResourceManager.GetString("MultilineStringEditorWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winforms Designer is not supported on this platform..
        /// </summary>
        public static string PlatformNotSupported_WinformsDesigner {
            get {
                return ResourceManager.GetString("PlatformNotSupported_WinformsDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTL_False.
        /// </summary>
        public static string RTL {
            get {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the path to the folder that will initially be selected in the FolderBrowserDialog..
        /// </summary>
        public static string SelectedPathEditorLabel {
            get {
                return ResourceManager.GetString("SelectedPathEditorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unknown).
        /// </summary>
        public static string ShortcutKeys_InvalidKey {
            get {
                return ResourceManager.GetString("ShortcutKeys_InvalidKey", resourceCulture);
            }
        }
    }
}
