//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms.Design.Resources; 
using System;


/// <summary>
///  A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class MaskDesignerDialog {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal MaskDesignerDialog() {
    }
    
    /// <summary>
    ///  Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new("System.Windows.Forms.Design.Resources.MaskDesignerDialog", typeof(MaskDesignerDialog).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///  Overrides the current thread's CurrentUICulture property for all
    ///  resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left, Right.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles btnCancel_Anchor {
        get {
            object obj = ResourceManager.GetObject("btnCancel.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Boolean similar to True.
    /// </summary>
    internal static bool btnCancel_AutoSize {
        get {
            object obj = ResourceManager.GetObject("btnCancel.AutoSize", resourceCulture);
            return ((bool)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=81,Y=0}.
    /// </summary>
    internal static System.Drawing.Point btnCancel_Location {
        get {
            object obj = ResourceManager.GetObject("btnCancel.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
    /// </summary>
    internal static System.Drawing.Size btnCancel_Size {
        get {
            object obj = ResourceManager.GetObject("btnCancel.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 1.
    /// </summary>
    internal static int btnCancel_TabIndex {
        get {
            object obj = ResourceManager.GetObject("btnCancel.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Cancel.
    /// </summary>
    internal static string btnCancel_Text {
        get {
            return ResourceManager.GetString("btnCancel.Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left, Right.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles btnOK_Anchor {
        get {
            object obj = ResourceManager.GetObject("btnOK.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Boolean similar to True.
    /// </summary>
    internal static bool btnOK_AutoSize {
        get {
            object obj = ResourceManager.GetObject("btnOK.AutoSize", resourceCulture);
            return ((bool)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
    /// </summary>
    internal static System.Drawing.Point btnOK_Location {
        get {
            object obj = ResourceManager.GetObject("btnOK.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
    /// </summary>
    internal static System.Drawing.Size btnOK_Size {
        get {
            object obj = ResourceManager.GetObject("btnOK.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 0.
    /// </summary>
    internal static int btnOK_TabIndex {
        get {
            object obj = ResourceManager.GetObject("btnOK.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to OK.
    /// </summary>
    internal static string btnOK_Text {
        get {
            return ResourceManager.GetString("btnOK.Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles checkBoxUseValidatingType_Anchor {
        get {
            object obj = ResourceManager.GetObject("checkBoxUseValidatingType.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Boolean similar to True.
    /// </summary>
    internal static bool checkBoxUseValidatingType_AutoSize {
        get {
            object obj = ResourceManager.GetObject("checkBoxUseValidatingType.AutoSize", resourceCulture);
            return ((bool)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=364,Y=1}.
    /// </summary>
    internal static System.Drawing.Point checkBoxUseValidatingType_Location {
        get {
            object obj = ResourceManager.GetObject("checkBoxUseValidatingType.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=114, Height=17}.
    /// </summary>
    internal static System.Drawing.Size checkBoxUseValidatingType_Size {
        get {
            object obj = ResourceManager.GetObject("checkBoxUseValidatingType.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 2.
    /// </summary>
    internal static int checkBoxUseValidatingType_TabIndex {
        get {
            object obj = ResourceManager.GetObject("checkBoxUseValidatingType.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to &amp;Use ValidatingType.
    /// </summary>
    internal static string checkBoxUseValidatingType_Text {
        get {
            return ResourceManager.GetString("checkBoxUseValidatingType.Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 160.
    /// </summary>
    internal static int dataFormatHeader_Width {
        get {
            object obj = ResourceManager.GetObject("dataFormatHeader.Width", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles lblHeader_Anchor {
        get {
            object obj = ResourceManager.GetObject("lblHeader.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Boolean similar to True.
    /// </summary>
    internal static bool lblHeader_AutoSize {
        get {
            object obj = ResourceManager.GetObject("lblHeader.AutoSize", resourceCulture);
            return ((bool)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
    /// </summary>
    internal static System.Drawing.Point lblHeader_Location {
        get {
            object obj = ResourceManager.GetObject("lblHeader.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=469, Height=13}.
    /// </summary>
    internal static System.Drawing.Size lblHeader_Size {
        get {
            object obj = ResourceManager.GetObject("lblHeader.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 0.
    /// </summary>
    internal static int lblHeader_TabIndex {
        get {
            object obj = ResourceManager.GetObject("lblHeader.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to &amp;Select a predefined mask description from the list below or
    ///  select Custom to define a custom mask..
    /// </summary>
    internal static string lblHeader_Text {
        get {
            return ResourceManager.GetString("lblHeader.Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles lblMask_Anchor {
        get {
            object obj = ResourceManager.GetObject("lblMask.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Boolean similar to True.
    /// </summary>
    internal static bool lblMask_AutoSize {
        get {
            object obj = ResourceManager.GetObject("lblMask.AutoSize", resourceCulture);
            return ((bool)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=3}.
    /// </summary>
    internal static System.Drawing.Point lblMask_Location {
        get {
            object obj = ResourceManager.GetObject("lblMask.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=35, Height=13}.
    /// </summary>
    internal static System.Drawing.Size lblMask_Size {
        get {
            object obj = ResourceManager.GetObject("lblMask.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 0.
    /// </summary>
    internal static int lblMask_TabIndex {
        get {
            object obj = ResourceManager.GetObject("lblMask.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to &amp;Mask:.
    /// </summary>
    internal static string lblMask_Text {
        get {
            return ResourceManager.GetString("lblMask.Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles lblTryIt_Anchor {
        get {
            object obj = ResourceManager.GetObject("lblTryIt.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Boolean similar to True.
    /// </summary>
    internal static bool lblTryIt_AutoSize {
        get {
            object obj = ResourceManager.GetObject("lblTryIt.AutoSize", resourceCulture);
            return ((bool)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=29}.
    /// </summary>
    internal static System.Drawing.Point lblTryIt_Location {
        get {
            object obj = ResourceManager.GetObject("lblTryIt.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=47, Height=13}.
    /// </summary>
    internal static System.Drawing.Size lblTryIt_Size {
        get {
            object obj = ResourceManager.GetObject("lblTryIt.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 3.
    /// </summary>
    internal static int lblTryIt_TabIndex {
        get {
            object obj = ResourceManager.GetObject("lblTryIt.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to &amp;Preview:.
    /// </summary>
    internal static string lblTryIt_Text {
        get {
            return ResourceManager.GetString("lblTryIt.Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles listViewCannedMasks_Anchor {
        get {
            object obj = ResourceManager.GetObject("listViewCannedMasks.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to .
    /// </summary>
    internal static string listViewCannedMasks_Columns {
        get {
            return ResourceManager.GetString("listViewCannedMasks.Columns", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to .
    /// </summary>
    internal static string listViewCannedMasks_Columns1 {
        get {
            return ResourceManager.GetString("listViewCannedMasks.Columns1", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to .
    /// </summary>
    internal static string listViewCannedMasks_Columns2 {
        get {
            return ResourceManager.GetString("listViewCannedMasks.Columns2", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Boolean similar to False.
    /// </summary>
    internal static bool listViewCannedMasks_LabelWrap {
        get {
            object obj = ResourceManager.GetObject("listViewCannedMasks.LabelWrap", resourceCulture);
            return ((bool)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=19}.
    /// </summary>
    internal static System.Drawing.Point listViewCannedMasks_Location {
        get {
            object obj = ResourceManager.GetObject("listViewCannedMasks.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=478, Height=198}.
    /// </summary>
    internal static System.Drawing.Size listViewCannedMasks_Size {
        get {
            object obj = ResourceManager.GetObject("listViewCannedMasks.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 1.
    /// </summary>
    internal static int listViewCannedMasks_TabIndex {
        get {
            object obj = ResourceManager.GetObject("listViewCannedMasks.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 160.
    /// </summary>
    internal static int maskDescriptionHeader_Width {
        get {
            object obj = ResourceManager.GetObject("maskDescriptionHeader.Width", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left, Right.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles maskedTextBox_Anchor {
        get {
            object obj = ResourceManager.GetObject("maskedTextBox.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=53,Y=26}.
    /// </summary>
    internal static System.Drawing.Point maskedTextBox_Location {
        get {
            object obj = ResourceManager.GetObject("maskedTextBox.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=293, Height=20}.
    /// </summary>
    internal static System.Drawing.Size maskedTextBox_Size {
        get {
            object obj = ResourceManager.GetObject("maskedTextBox.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 4.
    /// </summary>
    internal static int maskedTextBox_TabIndex {
        get {
            object obj = ResourceManager.GetObject("maskedTextBox.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left, Right.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles maskTryItTable_Anchor {
        get {
            object obj = ResourceManager.GetObject("maskTryItTable.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Boolean similar to True.
    /// </summary>
    internal static bool maskTryItTable_AutoSize {
        get {
            object obj = ResourceManager.GetObject("maskTryItTable.AutoSize", resourceCulture);
            return ((bool)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 3.
    /// </summary>
    internal static int maskTryItTable_ColumnCount {
        get {
            object obj = ResourceManager.GetObject("maskTryItTable.ColumnCount", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;
    ///  TableLayoutSettings&gt;&lt;Controls&gt;&lt;Control Name=&quot;checkBoxUseValidatingType&quot; Row=&quot;
    ///  0&quot; RowSpan=&quot;1&quot; Column=&quot;2&quot; ColumnSpan=&quot;1&quot; /&gt;&lt;Control Name=&quot;
    ///  lblMask&quot; Row=&quot;0&quot; RowSpan=&quot;1&quot; Column=&quot;0&quot; ColumnSpan=&quot;1&quot; /&gt;&lt;
    ///  Control Name=&quot;txtBoxMask&quot; Row=&quot;0&quot; RowSpan=&quot;1&quot; Column=&quot;
    ///  1&quot; ColumnSpan=&quot;1&quot; /&gt;&lt;Control Name=&quot;lblTryIt&quot; Row=&quot;
    ///  1&quot; RowSpan=&quot;1&quot; Column=&quot;0&quot; ColumnSpan=&quot;1&quot; /&gt;&lt;Control Name=&quot;
    ///  maskedTextBox&quot; Row=&quot;1&quot; RowSpan=&quot;1&quot; Column=&quot;1&quot; ColumnSpan=&quot;
    ///  1&quot; /&gt;&lt;/Controls&gt;&lt;Columns Styles=&quot;
    ///  AutoSize,0,Percent,100,Aut [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string maskTryItTable_LayoutSettings {
        get {
            return ResourceManager.GetString("maskTryItTable.LayoutSettings", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=223}.
    /// </summary>
    internal static System.Drawing.Point maskTryItTable_Location {
        get {
            object obj = ResourceManager.GetObject("maskTryItTable.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 2.
    /// </summary>
    internal static int maskTryItTable_RowCount {
        get {
            object obj = ResourceManager.GetObject("maskTryItTable.RowCount", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=478, Height=46}.
    /// </summary>
    internal static System.Drawing.Size maskTryItTable_Size {
        get {
            object obj = ResourceManager.GetObject("maskTryItTable.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 2.
    /// </summary>
    internal static int maskTryItTable_TabIndex {
        get {
            object obj = ResourceManager.GetObject("maskTryItTable.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Right.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles okCancelTableLayoutPanel_Anchor {
        get {
            object obj = ResourceManager.GetObject("okCancelTableLayoutPanel.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Boolean similar to True.
    /// </summary>
    internal static bool okCancelTableLayoutPanel_AutoSize {
        get {
            object obj = ResourceManager.GetObject("okCancelTableLayoutPanel.AutoSize", resourceCulture);
            return ((bool)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 2.
    /// </summary>
    internal static int okCancelTableLayoutPanel_ColumnCount {
        get {
            object obj = ResourceManager.GetObject("okCancelTableLayoutPanel.ColumnCount", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;
    ///  TableLayoutSettings&gt;&lt;Controls&gt;&lt;Control Name=&quot;btnCancel&quot; Row=&quot;
    ///  0&quot; RowSpan=&quot;1&quot; Column=&quot;1&quot; ColumnSpan=&quot;1&quot; /&gt;&lt;
    ///  Control Name=&quot;btnOK&quot; Row=&quot;0&quot; RowSpan=&quot;1&quot; Column=&quot;
    ///  0&quot; ColumnSpan=&quot;1&quot; /&gt;&lt;/Controls&gt;&lt;Columns Styles=&quot;
    ///  Percent,50,Percent,50&quot; /&gt;&lt;Rows Styles=&quot;AutoSize,0&quot; /&gt;&lt;/TableLayoutSettings&gt;.
    /// </summary>
    internal static string okCancelTableLayoutPanel_LayoutSettings {
        get {
            return ResourceManager.GetString("okCancelTableLayoutPanel.LayoutSettings", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=322,Y=278}.
    /// </summary>
    internal static System.Drawing.Point okCancelTableLayoutPanel_Location {
        get {
            object obj = ResourceManager.GetObject("okCancelTableLayoutPanel.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 1.
    /// </summary>
    internal static int okCancelTableLayoutPanel_RowCount {
        get {
            object obj = ResourceManager.GetObject("okCancelTableLayoutPanel.RowCount", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=156, Height=23}.
    /// </summary>
    internal static System.Drawing.Size okCancelTableLayoutPanel_Size {
        get {
            object obj = ResourceManager.GetObject("okCancelTableLayoutPanel.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 3.
    /// </summary>
    internal static int okCancelTableLayoutPanel_TabIndex {
        get {
            object obj = ResourceManager.GetObject("okCancelTableLayoutPanel.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles overarchingTableLayoutPanel_Anchor {
        get {
            object obj = ResourceManager.GetObject("overarchingTableLayoutPanel.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 1.
    /// </summary>
    internal static int overarchingTableLayoutPanel_ColumnCount {
        get {
            object obj = ResourceManager.GetObject("overarchingTableLayoutPanel.ColumnCount", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;
    ///  TableLayoutSettings&gt;&lt;Controls&gt;&lt;Control Name=&quot;maskTryItTable&quot; Row=&quot;3&quot;
    ///  RowSpan=&quot;1&quot; Column=&quot;0&quot; ColumnSpan=&quot;1&quot; /&gt;&lt;Control Name=&quot;
    ///  okCancelTableLayoutPanel&quot; Row=&quot;4&quot; RowSpan=&quot;1&quot; Column=&quot;0&quot; ColumnSpan=&quot;
    ///  1&quot; /&gt;&lt;Control Name=&quot;lblHeader&quot; Row=&quot;1&quot; RowSpan=&quot;1&quot; Column=&quot;
    ///  0&quot; ColumnSpan=&quot;1&quot; /&gt;&lt;Control Name=&quot;listViewCannedMasks&quot; Row=&quot;2&quot;
    ///  RowSpan=&quot;1&quot; Column=&quot;0&quot; ColumnSpan=&quot;1&quot; /&gt;&lt;/Controls&gt;&lt;
    ///  Columns Styles=&quot;Percent,50&quot; /&gt;&lt;Rows Styles=&quot;
    ///  AutoSize,0,AutoSize,0,Percent,50,AutoSize,0,AutoSize,0&quot; /&gt;&lt;/ [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string overarchingTableLayoutPanel_LayoutSettings {
        get {
            return ResourceManager.GetString("overarchingTableLayoutPanel.LayoutSettings", resourceCulture);
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=13}.
    /// </summary>
    internal static System.Drawing.Point overarchingTableLayoutPanel_Location {
        get {
            object obj = ResourceManager.GetObject("overarchingTableLayoutPanel.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 5.
    /// </summary>
    internal static int overarchingTableLayoutPanel_RowCount {
        get {
            object obj = ResourceManager.GetObject("overarchingTableLayoutPanel.RowCount", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=478, Height=301}.
    /// </summary>
    internal static System.Drawing.Size overarchingTableLayoutPanel_Size {
        get {
            object obj = ResourceManager.GetObject("overarchingTableLayoutPanel.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 0.
    /// </summary>
    internal static int overarchingTableLayoutPanel_TabIndex {
        get {
            object obj = ResourceManager.GetObject("overarchingTableLayoutPanel.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left, Right.
    /// </summary>
    internal static System.Windows.Forms.AnchorStyles txtBoxMask_Anchor {
        get {
            object obj = ResourceManager.GetObject("txtBoxMask.Anchor", resourceCulture);
            return ((System.Windows.Forms.AnchorStyles)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Point similar to {X=53,Y=0}.
    /// </summary>
    internal static System.Drawing.Point txtBoxMask_Location {
        get {
            object obj = ResourceManager.GetObject("txtBoxMask.Location", resourceCulture);
            return ((System.Drawing.Point)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Drawing.Size similar to {Width=293, Height=20}.
    /// </summary>
    internal static System.Drawing.Size txtBoxMask_Size {
        get {
            object obj = ResourceManager.GetObject("txtBoxMask.Size", resourceCulture);
            return ((System.Drawing.Size)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 1.
    /// </summary>
    internal static int txtBoxMask_TabIndex {
        get {
            object obj = ResourceManager.GetObject("txtBoxMask.TabIndex", resourceCulture);
            return ((int)(obj));
        }
    }
    
    /// <summary>
    ///  Looks up a localized resource of type System.Int32 similar to 150.
    /// </summary>
    internal static int validatingTypeHeader_Width {
        get {
            object obj = ResourceManager.GetObject("validatingTypeHeader.Width", resourceCulture);
            return ((int)(obj));
        }
    }
}
