//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms.Design.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Forms.Design.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy and move {0}.
        /// </summary>
        public static string BehaviorServiceCopyControl {
            get {
                return ResourceManager.GetString("BehaviorServiceCopyControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy and move {0} Controls.
        /// </summary>
        public static string BehaviorServiceCopyControls {
            get {
                return ResourceManager.GetString("BehaviorServiceCopyControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0}.
        /// </summary>
        public static string BehaviorServiceMoveControl {
            get {
                return ResourceManager.GetString("BehaviorServiceMoveControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0} Controls.
        /// </summary>
        public static string BehaviorServiceMoveControls {
            get {
                return ResourceManager.GetString("BehaviorServiceMoveControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double cannot be converted to a date..
        /// </summary>
        public static string CannotConvertDoubleToDate {
            get {
                return ResourceManager.GetString("CannotConvertDoubleToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer cannot be converted to a float..
        /// </summary>
        public static string CannotConvertIntToFloat {
            get {
                return ResourceManager.GetString("CannotConvertIntToFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled VT: {0}..
        /// </summary>
        public static string COM2UnhandledVT {
            get {
                return ResourceManager.GetString("COM2UnhandledVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format {0} components (alignment).
        /// </summary>
        public static string CommandSetAlignByPrimary {
            get {
                return ResourceManager.GetString("CommandSetAlignByPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align {0} components to grid.
        /// </summary>
        public static string CommandSetAlignToGrid {
            get {
                return ResourceManager.GetString("CommandSetAlignToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut {0} Components.
        /// </summary>
        public static string CommandSetCutMultiple {
            get {
                return ResourceManager.GetString("CommandSetCutMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} components.
        /// </summary>
        public static string CommandSetDelete
        {
            get
            {
                return ResourceManager.GetString("CommandSetDelete", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to The serialization store is closed.  New objects cannot be added to a closed store..
        /// </summary>
        public static string CodeDomComponentSerializationServiceClosedStore {
            get {
                return ResourceManager.GetString("CodeDomComponentSerializationServiceClosedStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing this command.\r\n{0}.
        /// </summary>
        public static string CommandSetError
        {
            get
            {
                return ResourceManager.GetString("CommandSetError", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Complete deserialization of {0} failed..
        /// </summary>
        public static string CodeDomComponentSerializationServiceDeserializationError {
            get {
                return ResourceManager.GetString("CodeDomComponentSerializationServiceDeserializationError", resourceCulture);

            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format {0} components (spacing).
        /// </summary>
        public static string CommandSetFormatSpacing {
            get {
                return ResourceManager.GetString("CommandSetFormatSpacing", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to This type of serialization store is not supported.  Use a store returned by the CreateStore method..
        /// </summary>
        public static string CodeDomComponentSerializationServiceUnknownStore {
            get {
                return ResourceManager.GetString("CodeDomComponentSerializationServiceUnknownStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste components.
        /// </summary>
        public static string CommandSetPaste {
            get {
                return ResourceManager.GetString("CommandSetPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size {0} components.
        /// </summary>
        public static string CommandSetSize {
            get {
                return ResourceManager.GetString("CommandSetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size {0} components to grid.
        /// </summary>
        public static string CommandSetSizeToGrid {
            get {
                return ResourceManager.GetString("CommandSetSizeToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown spacing command.
        /// </summary>
        public static string CommandSetUnknownSpacingCommand
        {
            get
            {
                return ResourceManager.GetString("CommandSetUnknownSpacingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding event &apos;{0}&apos;.
        /// </summary>
        public static string ComponentDesignerAddEvent {
            get {
                return ResourceManager.GetString("ComponentDesignerAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert value &apos;{0}&apos; to the type &apos;{1}&apos;..
        /// </summary>
        public static string DesignerActionPanel_CouldNotConvertValue {
            get {
                return ResourceManager.GetString("DesignerActionPanel_CouldNotConvertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find method &apos;{0}&apos;.
        /// </summary>
        public static string DesignerActionPanel_CouldNotFindMethod {
            get {
                return ResourceManager.GetString("DesignerActionPanel_CouldNotFindMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find property &apos;{0}&apos; on &apos;{1}&apos;..
        /// </summary>
        public static string DesignerActionPanel_CouldNotFindProperty {
            get {
                return ResourceManager.GetString("DesignerActionPanel_CouldNotFindProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Tasks.
        /// </summary>
        public static string DesignerActionPanel_DefaultPanelTitle {
            get {
                return ResourceManager.GetString("DesignerActionPanel_DefaultPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error using the dropdown: {0}.
        /// </summary>
        public static string DesignerActionPanel_ErrorActivatingDropDown {
            get {
                return ResourceManager.GetString("DesignerActionPanel_ErrorActivatingDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error invoking &apos;{0}&apos;.  Details: {1}.
        /// </summary>
        public static string DesignerActionPanel_ErrorInvokingAction {
            get {
                return ResourceManager.GetString("DesignerActionPanel_ErrorInvokingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting value &apos;{0}&apos; to property &apos;{1}&apos;.  Details: {2}.
        /// </summary>
        public static string DesignerActionPanel_ErrorSettingValue {
            get {
                return ResourceManager.GetString("DesignerActionPanel_ErrorSettingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to BeginDrag must succeed before calling drag functions..
        /// </summary>
        public static string DesignerBeginDragNotCalled {
            get {
                return ResourceManager.GetString("DesignerBeginDragNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove or destroy inherited component &apos;{0}&apos;..
        /// </summary>
        public static string DesignerHostCantDestroyInheritedComponent {
            get {
                return ResourceManager.GetString("DesignerHostCantDestroyInheritedComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add an instance of {0} to the designer because it would create a circular dependency.  Make sure that the type does not have the same namespace and type name as the root component {1}..
        /// </summary>
        public static string DesignerHostCyclicAdd {
            get {
                return ResourceManager.GetString("DesignerHostCyclicAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure initializing the designer.  It has no Component member..
        /// </summary>
        public static string DesignerHostDesignerNeedsComponent {
            get {
                return ResourceManager.GetString("DesignerHostDesignerNeedsComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting &apos;{0}&apos;..
        /// </summary>
        public static string DesignerHostDestroyComponentTransaction {
            get {
                return ResourceManager.GetString("DesignerHostDestroyComponentTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} is already in use by another component..
        /// </summary>
        public static string DesignerHostDuplicateName {
            get {
                return ResourceManager.GetString("DesignerHostDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component of type {0} could not be created.  Make sure the type implements IComponent and provides an appropriate public constructor.  Appropriate constructors either take no parameters or take a single IContainer parameter..
        /// </summary>
        public static string DesignerHostFailedComponentCreate {
            get {
                return ResourceManager.GetString("DesignerHostFailedComponentCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Description Available.
        /// </summary>
        public static string DesignerHostGenericTransactionName {
            get {
                return ResourceManager.GetString("DesignerHostGenericTransactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A designer loader has already been configured for this design surface..
        /// </summary>
        public static string DesignerHostLoaderSpecified {
            get {
                return ResourceManager.GetString("DesignerHostLoaderSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designer transaction &apos;{0}&apos; cannot be committed or canceled because nested transaction &apos;{1}&apos; is still active.  Commit or cancel the nested transaction first..
        /// </summary>
        public static string DesignerHostNestedTransaction {
            get {
                return ResourceManager.GetString("DesignerHostNestedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open a designer for the file because the class within it does not inherit from a class that can be visually designed..
        /// </summary>
        public static string DesignerHostNoBaseClass {
            get {
                return ResourceManager.GetString("DesignerHostNoBaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no designer for the class {0}..
        /// </summary>
        public static string DesignerHostNoTopLevelDesigner {
            get {
                return ResourceManager.GetString("DesignerHostNoTopLevelDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New components cannot be added while a designer is unloading..
        /// </summary>
        public static string DesignerHostUnloading {
            get {
                return ResourceManager.GetString("DesignerHostUnloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited control.
        /// </summary>
        public static string DesignerInherited {
            get {
                return ResourceManager.GetString("DesignerInherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited control (Private).
        /// </summary>
        public static string DesignerInheritedReadOnly {
            get {
                return ResourceManager.GetString("DesignerInheritedReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized Code Generation.
        /// </summary>
        public static string DesignerOptions_CodeGenDisplay {
            get {
                return ResourceManager.GetString("DesignerOptions_CodeGenDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Generation Settings.
        /// </summary>
        public static string DesignerOptions_CodeGenSettings {
            get {
                return ResourceManager.GetString("DesignerOptions_CodeGenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InSitu Editing.
        /// </summary>
        public static string DesignerOptions_EnableInSituEditingCat {
            get {
                return ResourceManager.GetString("DesignerOptions_EnableInSituEditingCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether InSitu editing is enabled..
        /// </summary>
        public static string DesignerOptions_EnableInSituEditingDesc {
            get {
                return ResourceManager.GetString("DesignerOptions_EnableInSituEditingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable InSitu Editing.
        /// </summary>
        public static string DesignerOptions_EnableInSituEditingDisplay {
            get {
                return ResourceManager.GetString("DesignerOptions_EnableInSituEditingDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the default X and Y grid setting on designers when LayoutMode  = SnapToGrid..
        /// </summary>
        public static string DesignerOptions_GridSizeDesc {
            get {
                return ResourceManager.GetString("DesignerOptions_GridSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Grid Cell Size.
        /// </summary>
        public static string DesignerOptions_GridSizeDisplayName {
            get {
                return ResourceManager.GetString("DesignerOptions_GridSizeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Settings.
        /// </summary>
        public static string DesignerOptions_LayoutSettings {
            get {
                return ResourceManager.GetString("DesignerOptions_LayoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether designer smart tag windows should be shown by default..
        /// </summary>
        public static string DesignerOptions_ObjectBoundSmartTagAutoShow {
            get {
                return ResourceManager.GetString("DesignerOptions_ObjectBoundSmartTagAutoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Open Smart Tags.
        /// </summary>
        public static string DesignerOptions_ObjectBoundSmartTagAutoShowDisplayName {
            get {
                return ResourceManager.GetString("DesignerOptions_ObjectBoundSmartTagAutoShowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Bound Smart Tag Settings.
        /// </summary>
        public static string DesignerOptions_ObjectBoundSmartTagSettings {
            get {
                return ResourceManager.GetString("DesignerOptions_ObjectBoundSmartTagSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled optimized code generation.  Some controls may not be compatible with this mode.  For this change to take effect, Visual Studio must be closed and re-opened..
        /// </summary>
        public static string DesignerOptions_OptimizedCodeGen {
            get {
                return ResourceManager.GetString("DesignerOptions_OptimizedCodeGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether designers should display a sizing grid when LayoutMode = SnapToGrid..
        /// </summary>
        public static string DesignerOptions_ShowGridDesc {
            get {
                return ResourceManager.GetString("DesignerOptions_ShowGridDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        public static string DesignerOptions_ShowGridDisplayName {
            get {
                return ResourceManager.GetString("DesignerOptions_ShowGridDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether designers should snap to grid dots when LayoutMode = SnapToGrid..
        /// </summary>
        public static string DesignerOptions_SnapToGridDesc {
            get {
                return ResourceManager.GetString("DesignerOptions_SnapToGridDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to Grid.
        /// </summary>
        public static string DesignerOptions_SnapToGridDisplayName {
            get {
                return ResourceManager.GetString("DesignerOptions_SnapToGridDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether designers should show smart tag popup windows..
        /// </summary>
        public static string DesignerOptions_UseSmartTags {
            get {
                return ResourceManager.GetString("DesignerOptions_UseSmartTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether designers should use snap lines.  If true, snap lines will be used as guides.  If false, grid lines will be used..
        /// </summary>
        public static string DesignerOptions_UseSnapLines {
            get {
                return ResourceManager.GetString("DesignerOptions_UseSnapLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container cannot be disposed at design time..
        /// </summary>
        public static string DesignSurfaceContainerDispose {
            get {
                return ResourceManager.GetString("DesignSurfaceContainerDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a view for this design surface because the designer is not loaded..
        /// </summary>
        public static string DesignSurfaceDesignerNotLoaded {
            get {
                return ResourceManager.GetString("DesignSurfaceDesignerNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the document.  Fix the error, and then try loading the document again.  The error message follows:\r\n\r\n{0}.
        /// </summary>
        public static string DesignSurfaceFatalError {
            get {
                return ResourceManager.GetString("DesignSurfaceFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designer loader did not provide a root component but has not indicated why..
        /// </summary>
        public static string DesignSurfaceNoRootComponent {
            get {
                return ResourceManager.GetString("DesignSurfaceNoRootComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designer loaded, but it does not offer a view compatible with this design surface..
        /// </summary>
        public static string DesignSurfaceNoSupportedTechnology {
            get {
                return ResourceManager.GetString("DesignSurfaceNoSupportedTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service {0} cannot be removed from the service container..
        /// </summary>
        public static string DesignSurfaceServiceIsFixed {
            get {
                return ResourceManager.GetString("DesignSurfaceServiceIsFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Component.
        /// </summary>
        public static string DotNET_ComponentType {
            get {
                return ResourceManager.GetString("DotNET_ComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag {0} components.
        /// </summary>
        public static string DragDropDragComponents
        {
            get
            {
                return ResourceManager.GetString("DragDropDragComponents", resourceCulture);
            }
        }        ///   Looks up a localized string similar to This IDataObject doesn&apos;t support SetData..
        /// </summary>
        public static string DragDropSetDataError {
            get {
                return ResourceManager.GetString("DragDropSetDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extender provider {0} has already been added as an extender.  Adding another would result in duplicate properties..
        /// </summary>
        public static string ExtenderProviderServiceDuplicateProvider {
            get {
                return ResourceManager.GetString("ExtenderProviderServiceDuplicateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0}.
        /// </summary>
        public static string DragDropMoveComponent
        {
            get
            {
                return ResourceManager.GetString("DragDropMoveComponent", resourceCulture);
            }
        }        ///   Looks up a localized string similar to Read-Only.
        /// </summary>
        public static string InheritanceServiceReadOnlyCollection {
            get {
                return ResourceManager.GetString("InheritanceServiceReadOnlyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0} components.
        /// </summary>
        public static string DragDropMoveComponents
        {
            get
            {
                return ResourceManager.GetString("DragDropMoveComponents", resourceCulture);
            }
        }        ///   Looks up a localized string similar to This method/object is not implemented by design..
        /// </summary>
        public static string NotImplementedByDesign {
            get {
                return ResourceManager.GetString("NotImplementedByDesign", resourceCulture);
            }
        }
        
        /// <summary>        
        ///   Looks up a localized string similar to Winforms Designer is not supported on this platform..
        /// </summary>
        public static string PlatformNotSupported_WinformsDesigner {
            get {
                return ResourceManager.GetString("PlatformNotSupported_WinformsDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size {0}.
        /// </summary>
        public static string DragDropSizeComponent
        {
            get
            {
                return ResourceManager.GetString("DragDropSizeComponent", resourceCulture);
            }
        }        ///   Looks up a localized string similar to You cannot create a new session because this serialization manager already has an active serialization session..
        /// </summary>
        public static string SerializationManagerAreadyInSession {
            get {
                return ResourceManager.GetString("SerializationManagerAreadyInSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size {0} components.
        /// </summary>
        public static string DragDropSizeComponents
        {
            get
            {
                return ResourceManager.GetString("DragDropSizeComponents", resourceCulture);
            }
        }        ///   Looks up a localized string similar to Duplicate declaration of member &apos;{0}&apos;.
        /// </summary>
        public static string SerializationManagerDuplicateComponentDecl {
            get {
                return ResourceManager.GetString("SerializationManagerDuplicateComponentDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is already used by another object..
        /// </summary>
        public static string SerializationManagerNameInUse {
            get {
                return ResourceManager.GetString("SerializationManagerNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not have a constructor with parameters of types {1}..
        /// </summary>
        public static string SerializationManagerNoMatchingCtor {
            get {
                return ResourceManager.GetString("SerializationManagerNoMatchingCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method cannot be invoked because the serialization manager does not have an active serialization session..
        /// </summary>
        public static string SerializationManagerNoSession {
            get {
                return ResourceManager.GetString("SerializationManagerNoSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot name the object &apos;{0}&apos; because it is already named &apos;{1}&apos;..
        /// </summary>
        public static string SerializationManagerObjectHasName {
            get {
                return ResourceManager.GetString("SerializationManagerObjectHasName", resourceCulture);

            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTL_False.
        /// </summary>
        public static string RTL
        {
            get
            {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to This method cannot be invoked because the serialization manager has an active serialization session..
        /// </summary>
        public static string SerializationManagerWithinSession {
            get {
                return ResourceManager.GetString("SerializationManagerWithinSession", resourceCulture);

            }
        }
        
        /// <summary>

        ///   Looks up a localized string similar to Argument should be a non-empty string..
        /// </summary>
        public static string ToolboxItemInvalidKey {
            get {
                return ResourceManager.GetString("ToolboxItemInvalidKey", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Elements of type {0} are not supported.  The serializer expects the element to be one of the following: {1}..
        /// </summary>
        public static string SerializerBadElementTypes {
            get {
                return ResourceManager.GetString("SerializerBadElementTypes", resourceCulture);

            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} requires an argument of type {1}..
        /// </summary>
        public static string ToolboxItemInvalidPropertyType
        {
            get
            {
                return ResourceManager.GetString("ToolboxItemInvalidPropertyType", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to The field &apos;{0}&apos; could not be found on the target object.  Make sure that the field is defined as an instance variable on the target object and has the correct scope..
        /// </summary>
        public static string SerializerFieldTargetEvalFailed {
            get {
                return ResourceManager.GetString("SerializerFieldTargetEvalFailed", resourceCulture);

            }
        }
        
        /// <summary>

        ///   Looks up a localized string similar to Toolbox item cannot be modified..
        /// </summary>
        public static string ToolboxItemLocked {
            get {
                return ResourceManager.GetString("ToolboxItemLocked", resourceCulture);
            }
        }

        ///   Looks up a localized string similar to Array rank &apos;{0}&apos; is too high.  Visual Studio can only save and load arrays with a rank of 1..
        /// </summary>
        public static string SerializerInvalidArrayRank {
            get {
                return ResourceManager.GetString("SerializerInvalidArrayRank", resourceCulture);

            }
        }
        
        /// <summary>

        ///   Looks up a localized string similar to Data type {0} is not serializable. Items added to a property dictionary must be serializable..
        /// </summary>
        public static string ToolboxItemValueNotSerializable {
            get {
                return ResourceManager.GetString("ToolboxItemValueNotSerializable", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Code statements for the object &apos;{0}&apos; were lost during serialization.  This may have been a result of another object misbehaving during serialization..
        /// </summary>
        public static string SerializerLostStatements {
            get {
                return ResourceManager.GetString("SerializerLostStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members of type &apos;{0}&apos; cannot be serialized..
        /// </summary>
        public static string SerializerMemberTypeNotSerializable {
            get {
                return ResourceManager.GetString("SerializerMemberTypeNotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source code contains a reference to the class definition, but the class definition cannot be found..
        /// </summary>
        public static string SerializerNoRootExpression {
            get {
                return ResourceManager.GetString("SerializerNoRootExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Arrange Tray Icons.
        /// </summary>
        public static string TrayAutoArrange
        {
            get
            {
                return ResourceManager.GetString("TrayAutoArrange", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to The object &apos;{0}&apos; failed to serialize itself.  It may not support code generation..
        /// </summary>
        public static string SerializerNoSerializerForComponent {
            get {
                return ResourceManager.GetString("SerializerNoSerializerForComponent", resourceCulture);
            }
        }
        
        /// <summary>

        ///   Looks up a localized string similar to Line Up Tray Icons.
        /// </summary>
        public static string TrayLineUpIcons {
            get {
                return ResourceManager.GetString("TrayLineUpIcons", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has no event named &apos;{1}&apos;..
        /// </summary>
        public static string SerializerNoSuchEvent {
            get {
                return ResourceManager.GetString("SerializerNoSuchEvent", resourceCulture);

            }
        }
        
        /// <summary>

        ///   Looks up a localized string similar to Show Large or Small Icons.
        /// </summary>
        public static string TrayShowLargeIcons {
            get {
                return ResourceManager.GetString("TrayShowLargeIcons", resourceCulture);
            } 
}
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has no field named &apos;{1}&apos;..
        /// </summary>
        public static string SerializerNoSuchField {
            get {
                return ResourceManager.GetString("SerializerNoSuchField", resourceCulture);

            }
        }
        
        /// <summary>

        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string UIServiceHelper_ErrorCaption {
            get {
                return ResourceManager.GetString("UIServiceHelper_ErrorCaption", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has no property named &apos;{1}&apos;..
        /// </summary>
        public static string SerializerNoSuchProperty {
            get {
                return ResourceManager.GetString("SerializerNoSuchProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading resources from the resource file for the culture {0}: {1}.
        /// </summary>
        public static string SerializerResourceException {
            get {
                return ResourceManager.GetString("SerializerResourceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading resources from the resource file for the default culture: {0}.
        /// </summary>
        public static string SerializerResourceExceptionInvariant {
            get {
                return ResourceManager.GetString("SerializerResourceExceptionInvariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find type &apos;{0}&apos;.  Please make sure that the assembly that contains this type is referenced.  If this type is a part of your development project, make sure that the project has been successfully built using settings for your current platform or Any CPU..
        /// </summary>
        public static string SerializerTypeNotFound {
            get {
                return ResourceManager.GetString("SerializerTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable &apos;{0}&apos; is either undeclared or was never assigned..
        /// </summary>
        public static string SerializerUndeclaredName {
            get {
                return ResourceManager.GetString("SerializerUndeclaredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not available in the target framework..
        /// </summary>
        public static string TypeNotFoundInTargetFramework {
            get {
                return ResourceManager.GetString("TypeNotFoundInTargetFramework", resourceCulture);

            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Component.
        /// </summary>
        public static string UndoEngineComponentAdd0 {
            get {
                return ResourceManager.GetString("UndoEngineComponentAdd0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        public static string UndoEngineComponentAdd1 {
            get {
                return ResourceManager.GetString("UndoEngineComponentAdd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Component.
        /// </summary>
        public static string UndoEngineComponentChange0 {
            get {
                return ResourceManager.GetString("UndoEngineComponentChange0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change {0}.
        /// </summary>
        public static string UndoEngineComponentChange1 {
            get {
                return ResourceManager.GetString("UndoEngineComponentChange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change {0}.{1}.
        /// </summary>
        public static string UndoEngineComponentChange2 {
            get {
                return ResourceManager.GetString("UndoEngineComponentChange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Component.
        /// </summary>
        public static string UndoEngineComponentRemove0 {
            get {
                return ResourceManager.GetString("UndoEngineComponentRemove0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}.
        /// </summary>
        public static string UndoEngineComponentRemove1 {
            get {
                return ResourceManager.GetString("UndoEngineComponentRemove1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename {0} to {1}.
        /// </summary>
        public static string UndoEngineComponentRename {
            get {
                return ResourceManager.GetString("UndoEngineComponentRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service {0} is required but could not be found.  If you have removed this service ensure that you provide a replacement..
        /// </summary>
        public static string UndoEngineMissingService {
            get {
                return ResourceManager.GetString("UndoEngineMissingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented..
        /// </summary>
        public static string UnsafeNativeMethodsNotImplemented {
            get {
                return ResourceManager.GetString("UnsafeNativeMethodsNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;couldn&apos;t find resource string &quot;WindowsFormsAddEvent&quot;&gt;.
        /// </summary>
        public static string WindowsFormsAddEvent {
            get {
                return ResourceManager.GetString("WindowsFormsAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal center of {0} component(s).
        /// </summary>
        public static string WindowsFormsCommandCenterX {
            get {
                return ResourceManager.GetString("WindowsFormsCommandCenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical center of {0} component(s).
        /// </summary>
        public static string WindowsFormsCommandCenterY {
            get {
                return ResourceManager.GetString("WindowsFormsCommandCenterY", resourceCulture);
            }
        }
    }
}
