// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// This file is used by Code Analysis to maintain SuppressMessage

[assembly: SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "Public API", Scope = "type", Target = "~T:System.Windows.Forms.VisualStyles.TextMetrics")]
[assembly: SuppressMessage("Naming", "CA1725:Parameter names should match base declaration", Justification = "Public API", Scope = "member", Target = "~M:System.Windows.Forms.Message.Equals(System.Object)~System.Boolean")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLButtonElementEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLAnchorEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLAreaEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLControlElementEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLDocumentEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLElementEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLFormElementEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLFrameSiteEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLImgEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLInputFileElementEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLInputImageEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLInputTextElementEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLLabelEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLLinkElementEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLMapEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLMarqueeElementEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLOptionButtonElementEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLScriptEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLSelectElementEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLStyleElementEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLTableEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLTextContainerEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.Mshtml.DHTMLWindowEvents2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1302:Interface names should begin with I", Justification = "External name", Scope = "type", Target = "~T:Interop.SHDocVw.DWebBrowserEvents2")]
