// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#nullable disable

using System.Drawing;

namespace System.Windows.Forms.Tests;

public class ToolStripDropDownMenuTests
{
    [WinFormsFact]
    public void ToolStripDropDownMenu_Constructor()
    {
        using ToolStripDropDownMenu menu = new();

        menu.Should().NotBeNull();
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ConstructorOwnerItemBool()
    {
        using ToolStripButton owner = new();
        bool isAutoGenerated = true;

        using ToolStripDropDownMenu menu = new(owner, isAutoGenerated);

        menu.Should().NotBeNull();
        menu.OwnerItem.Should().Be(owner);
        menu.IsAutoGenerated.Should().BeTrue();
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ScrollInternalDown_LastItemDisplayed_DisablesDownScrollButton()
    {
        using ToolStripButton owner = new();
        using SubToolStripDropDownMenu menu = new(owner, isAutoGenerated: true)
        {
            // Use a full-item viewport to make the boundary condition deterministic:
            // first item is fully above the viewport, last item is fully visible.
            TestDisplayRectangle = new Rectangle(0, 20, 100, 20)
        };

        ToolStripItem firstItem = menu.Items.Add("First");
        ToolStripItem lastItem = menu.Items.Add("Last");

        // Enabling scroll buttons triggers internal position restoration logic.
        // Do this first, then set explicit bounds for deterministic visibility checks.
        menu.SetRequiresScrollButtons(true);

        firstItem.SetBounds(new Rectangle(0, 0, 80, 20));
        lastItem.SetBounds(new Rectangle(0, 20, 80, 20));

        // The real scroll-button pipeline should leave the down button disabled
        // when the last item is already visible, and a subsequent click should be a no-op.
        Record.Exception(menu.ScrollDown).Should().BeNull();
        menu.DownScrollButton.Enabled.Should().BeFalse();
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ScrollInternalDown_LastItemVisibleInMultiItemViewport_DisablesDownScrollButton()
    {
        using ToolStripButton owner = new();
        using SubToolStripDropDownMenu menu = new(owner, isAutoGenerated: true)
        {
            // Make room for multiple full items so the last item can be visible
            // while the first displayed item is not the last index.
            TestDisplayRectangle = new Rectangle(0, 20, 100, 40)
        };

        ToolStripItem firstItem = menu.Items.Add("First");
        ToolStripItem middleItem = menu.Items.Add("Middle");
        ToolStripItem lastItem = menu.Items.Add("Last");

        // Enabling scroll buttons triggers internal position restoration logic.
        // Do this first, then set explicit bounds for deterministic visibility checks.
        menu.SetRequiresScrollButtons(true);
        firstItem.SetBounds(new Rectangle(0, 0, 80, 20));
        middleItem.SetBounds(new Rectangle(0, 20, 80, 20));
        lastItem.SetBounds(new Rectangle(0, 40, 80, 20));

        // At this boundary the middle and last items are visible, so scrolling down
        // should already be disabled even though the first displayed item is not last.
        Record.Exception(menu.ScrollDown).Should().BeNull();
        menu.DownScrollButton.Enabled.Should().BeFalse();
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ChangeSelection_ItemAtDisplayBottom_DoesNotScroll()
    {
        using ToolStripButton owner = new();
        using SubToolStripDropDownMenu menu = new(owner, isAutoGenerated: true)
        {
            TestDisplayRectangle = new Rectangle(0, 0, 100, 40)
        };

        ToolStripItem firstItem = menu.Items.Add("First");
        ToolStripItem secondItem = menu.Items.Add("Second");

        firstItem.SetBounds(new Rectangle(0, 0, 80, 20));
        secondItem.SetBounds(new Rectangle(0, 20, 80, 20));

        menu.InvokeChangeSelection(secondItem);

        menu.ScrollCalled.Should().BeFalse();
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ScrollButtons_DoNotSupportItemClick()
    {
        using ToolStripButton owner = new();
        using SubToolStripDropDownMenu menu = new(owner, isAutoGenerated: true)
        {
            TestDisplayRectangle = new Rectangle(0, 0, 100, 40)
        };

        _ = menu.UpScrollButton;
        _ = menu.DownScrollButton;

        // Scroll buttons are navigation UI and must not route ItemClick, otherwise
        // ToolStripDropDown.AutoClose can dismiss the dropdown while scrolling.
        menu.UpScrollButton.SupportsItemClick.Should().BeFalse();
        menu.DownScrollButton.SupportsItemClick.Should().BeFalse();
    }

    private class SubToolStripDropDownMenu : ToolStripDropDownMenu
    {
        internal SubToolStripDropDownMenu(ToolStripItem ownerItem, bool isAutoGenerated)
            : base(ownerItem, isAutoGenerated)
        {
        }

        internal Rectangle TestDisplayRectangle { get; set; }
        internal bool ScrollCalled { get; private set; }

        public override Rectangle DisplayRectangle => TestDisplayRectangle;

        internal void SetRequiresScrollButtons(bool value) => base.RequiresScrollButtons = value;

        internal override void ScrollInternal(int delta)
        {
            ScrollCalled = true;
            base.ScrollInternal(delta);
        }

        internal void InvokeChangeSelection(ToolStripItem item) => base.ChangeSelection(item);

        internal void ScrollDown() => ScrollInternal(up: false);
    }
}
