// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#nullable disable

using System.Drawing;
using System.Reflection;

namespace System.Windows.Forms.Tests;

public class ToolStripDropDownMenuTests
{
    [WinFormsFact]
    public void ToolStripDropDownMenu_Constructor()
    {
        using ToolStripDropDownMenu menu = new();

        menu.Should().NotBeNull();
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ConstructorOwnerItemBool()
    {
        using ToolStripButton owner = new();
        bool isAutoGenerated = true;

        using ToolStripDropDownMenu menu = new(owner, isAutoGenerated);

        menu.Should().NotBeNull();
        menu.OwnerItem.Should().Be(owner);
        menu.IsAutoGenerated.Should().BeTrue();
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ScrollInternalDown_LastItemDisplayed_DisablesDownScrollButton()
    {
        using ToolStripButton owner = new();
        using SubToolStripDropDownMenu menu = new(owner, isAutoGenerated: true)
        {
            // Use a full-item viewport to make the boundary condition deterministic:
            // first item is fully above the viewport, last item is fully visible.
            TestDisplayRectangle = new Rectangle(0, 20, 100, 20)
        };

        ToolStripItem firstItem = menu.Items.Add("First");
        ToolStripItem lastItem = menu.Items.Add("Last");

        // Enabling scroll buttons triggers internal position restoration logic.
        // Do this first, then set explicit bounds for deterministic visibility checks.
        menu.SetRequiresScrollButtons(true);

        firstItem.SetBounds(new Rectangle(0, 0, 80, 20));
        lastItem.SetBounds(new Rectangle(0, 20, 80, 20));

        // The real scroll-button pipeline should leave the down button disabled
        // when the last item is already visible, and a subsequent click should be a no-op.
        Record.Exception(menu.ScrollDown).Should().BeNull();
        menu.DownScrollButton.Enabled.Should().BeFalse();
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ScrollInternalDown_LastItemVisibleInMultiItemViewport_EnablesDownScrollButton()
    {
        using ToolStripButton owner = new();
        using SubToolStripDropDownMenu menu = new(owner, isAutoGenerated: true)
        {
            // Viewport starts at Y=0, so the anchor is always the first item.
            TestDisplayRectangle = new Rectangle(0, 0, 100, 40)
        };

        ToolStripItem firstItem = menu.Items.Add("First");
        ToolStripItem middleItem = menu.Items.Add("Middle");
        ToolStripItem lastItem = menu.Items.Add("Last");

        // SetRequiresScrollButtons triggers internal anchor logic; set bounds after for deterministic layout.
        menu.SetRequiresScrollButtons(true);
        firstItem.SetBounds(new Rectangle(0, 0, 80, 18));
        middleItem.SetBounds(new Rectangle(0, 24, 80, 18));
        lastItem.SetBounds(new Rectangle(0, 46, 80, 18));

        // After setting bounds, recompute scroll button status.
        menu.RefreshScrollButtonStatus();
        menu.UpScrollButton.Enabled.Should().BeFalse("Up should be disabled when the first item is the anchor");
        menu.DownScrollButton.Enabled.Should().BeTrue("Down should be enabled when more items are below the anchor");

        // First scroll: anchor moves to middle item, last is still not fully visible, so down remains enabled.
        Record.Exception(menu.ScrollDown).Should().BeNull();
        menu.RefreshScrollButtonStatus();
        menu.UpScrollButton.Enabled.Should().BeTrue("Up should be enabled after scrolling down from the first item");
        menu.DownScrollButton.Enabled.Should().BeTrue("Down should still be enabled with last item below the anchor");

        // Second scroll: anchor moves to last item, all items are now visible, so down should become disabled.
        Record.Exception(menu.ScrollDown).Should().BeNull();
        menu.RefreshScrollButtonStatus();
        menu.DownScrollButton.Enabled.Should().BeFalse("Down should be disabled when the last item is fully visible");
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ChangeSelection_ItemAtDisplayBottom_DoesNotScroll()
    {
        using ToolStripButton owner = new();
        using SubToolStripDropDownMenu menu = new(owner, isAutoGenerated: true)
        {
            TestDisplayRectangle = new Rectangle(0, 0, 100, 40)
        };

        ToolStripItem firstItem = menu.Items.Add("First");
        ToolStripItem secondItem = menu.Items.Add("Second");

        firstItem.SetBounds(new Rectangle(0, 0, 80, 20));
        secondItem.SetBounds(new Rectangle(0, 20, 80, 20));

        menu.InvokeChangeSelection(secondItem);

        menu.ScrollCalled.Should().BeFalse();
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ScrollButtons_DoNotSupportItemClick()
    {
        using ToolStripButton owner = new();
        using SubToolStripDropDownMenu menu = new(owner, isAutoGenerated: true)
        {
            TestDisplayRectangle = new Rectangle(0, 0, 100, 40)
        };

        _ = menu.UpScrollButton;
        _ = menu.DownScrollButton;

        // Scroll buttons are navigation UI and must not route ItemClick, otherwise
        // ToolStripDropDown.AutoClose can dismiss the dropdown while scrolling.
        menu.UpScrollButton.SupportsItemClick.Should().BeFalse();
        menu.DownScrollButton.SupportsItemClick.Should().BeFalse();
    }

    [WinFormsFact]
    public void ToolStripDropDownMenu_ScrollButtonsStatus_WithUnavailableInterleavedItems_UsesAvailableItemsOnly()
    {
        using ToolStripButton owner = new();
        using SubToolStripDropDownMenu menu = new(owner, isAutoGenerated: true)
        {
            // Single-item viewport: only one item visible at a time.
            TestDisplayRectangle = new Rectangle(0, 0, 100, 20)
        };

        ToolStripItem firstItem = menu.Items.Add("First");
        ToolStripItem hiddenMiddleItem = menu.Items.Add("HiddenMiddle");
        ToolStripItem lastItem = menu.Items.Add("Last");

        menu.SetRequiresScrollButtons(true);

        firstItem.SetBounds(new Rectangle(0, 0, 80, 20));
        hiddenMiddleItem.SetBounds(new Rectangle(0, 20, 80, 20));
        lastItem.SetBounds(new Rectangle(0, 40, 80, 20));
        hiddenMiddleItem.Available = false;

        // Initial state: firstItem is visible, up is disabled, down is enabled (can scroll to lastItem)
        menu.RefreshScrollButtonStatus();
        menu.UpScrollButton.Enabled.Should().BeFalse("Up should be disabled when first available item is visible");
        menu.DownScrollButton.Enabled.Should().BeTrue("Down should be enabled when more available items are below");

        // Scroll down: lastItem becomes visible, up is enabled, down is disabled (no more items below)
        Record.Exception(menu.ScrollDown).Should().BeNull();
        menu.RefreshScrollButtonStatus();
        menu.UpScrollButton.Enabled.Should().BeTrue("Up should be enabled after scrolling down to last available item");
        menu.DownScrollButton.Enabled.Should().BeFalse("Down should be disabled when last available item is visible");

        // Scroll up: firstItem becomes visible again, up is disabled, down is enabled
        Record.Exception(() => menu.ScrollInternal(up: true)).Should().BeNull();
        menu.RefreshScrollButtonStatus();
        menu.UpScrollButton.Enabled.Should().BeFalse("Up should be disabled after scrolling back to first available item");
        menu.DownScrollButton.Enabled.Should().BeTrue("Down should be enabled after scrolling up from last available item");
    }

    private class SubToolStripDropDownMenu : ToolStripDropDownMenu
    {
        internal SubToolStripDropDownMenu(ToolStripItem ownerItem, bool isAutoGenerated)
            : base(ownerItem, isAutoGenerated)
        {
        }

        internal Rectangle TestDisplayRectangle { get; set; }
        internal bool ScrollCalled { get; private set; }

        public override Rectangle DisplayRectangle => TestDisplayRectangle;

        internal void SetRequiresScrollButtons(bool value) => base.RequiresScrollButtons = value;

        internal override void ScrollInternal(int delta)
        {
            ScrollCalled = true;
            base.ScrollInternal(delta);
        }

        internal void RefreshScrollButtonStatus()
        {
            MethodInfo updateScrollButtonStatus = typeof(ToolStripDropDownMenu)
                .GetMethod("UpdateScrollButtonStatus", BindingFlags.Instance | BindingFlags.NonPublic);

            updateScrollButtonStatus.Should().NotBeNull();
            updateScrollButtonStatus.Invoke(this, null);
        }

        internal void InvokeChangeSelection(ToolStripItem item) => base.ChangeSelection(item);

        internal void ScrollDown() => ScrollInternal(up: false);
    }
}
