name: API or feature suggestion
description: Propose a change to the public API surface
labels: ["untriaged", "api-suggestion"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to put the proposal forward!

        Please read https://github.com/dotnet/winforms/blob/main/docs/issue-guide.md#feature-and-api-suggestions and understand the API Review process before proceeding further.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. E.g., _I'm always frustrated when..._.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Describe the solution you'd like and alternatives you've considered
      description: |
        A clear and concise description of what you want to happen. This includes:
        - Description of what API need to be added or changed.
        - Code that shows the surface area of the API.
        - Code that shows real world scenarios, and how they would otherwise be handled.
        - Details showing the usage/consumption of the proposed new API, and alternatives (e.g., not having this API).
        - Any other context or screenshots about the feature request here.

        :exclamation: Read https://github.com/dotnet/winforms/blob/main/docs/issue-guide.md for more details, and check out the already [approved API proposals](https://github.com/dotnet/winforms/issues?q=label%3Aapi-approved).
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Will this feature affect UI controls?
      description: |
        If yes, describe the following:

        - Will VS Designer need to support the feature? If yes, describe how you expect it to fun—Åtion.
        - What impact will it have on accessibility?
        - Will this feature need to be localized or be localizable?
    validations:
      required: true
