// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Runtime.CompilerServices;

// internal UITypeEditors
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.BindingNavigatorDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.BindingSourceDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ColumnHeaderCollectionEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.DataMemberFieldConverter))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.DataGridViewCellStyleEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.DataGridViewColumnTypeEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.DataSourceListEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.FormatStringEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.HelpNamespaceEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ImageCollectionEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ImageIndexEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.LinkAreaEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ListControlStringCollectionEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ListViewGroupCollectionEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ListViewItemCollectionEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ListViewSubItemCollectionEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.MaskPropertyEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.MaskedTextBoxTextEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.StyleCollectionEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.SelectedPathEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.StringArrayEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.StringCollectionEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TabPageCollectionEditor))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TreeNodeCollectionEditor))]

// internal serializers
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ControlCodeDomSerializer))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.DataGridViewRowCollectionCodeDomSerializer))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TableLayoutControlCollectionCodeDomSerializer))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TableLayoutPanelCodeDomSerializer))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ToolStripCodeDomSerializer))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ToolStripMenuItemCodeDomSerializer))]

// internal designers
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ButtonBaseDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ComboBoxDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.DataGridViewDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.DataGridViewColumnDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.DataGridViewComboBoxColumnDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.DateTimePickerDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.FormDocumentDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.FlowPanelDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.GroupBoxDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ImageListDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.LabelDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ListBoxDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ListViewDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.MaskedTextBoxDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.MonthCalendarDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.NotifyIconDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.PanelDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.PropertyGridDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.PictureBoxDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.PrintDialogDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.RadioButtonDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.RichTextBoxDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.SaveFileDialogDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.SplitContainerDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.SplitterPanelDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.SplitterDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.FlowLayoutPanelDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.FolderBrowserDialogDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TabControlDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TableLayoutPanelDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TabPageDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ToolStripContainerDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ToolStripContentPanelDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ToolStripPanelDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TextBoxBaseDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TextBoxDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ToolStripDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ToolStripDropDownDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ToolStripDropDownItemDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ToolStripItemDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.ToolStripMenuItemDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TrackBarDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TreeViewDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.UpDownBaseDesigner))]
[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.UserControlDocumentDesigner))]

[assembly: TypeForwardedTo(typeof(System.Windows.Forms.Design.TabOrder))]

[assembly: TypeForwardedTo(typeof(System.Resources.Tools.StronglyTypedResourceBuilder))]
[assembly: TypeForwardedTo(typeof(System.Resources.Tools.ITargetAwareCodeDomProvider))]
