parameters:

  # Needed because agent pool can't be read from a user-defined variable (Azure DevOps limitation)
  agentPool: dotnet-external-temp

  # Needed because runAsPublic is used in template expressions, which can't read from user-defined variables
  runAsPublic: true

jobs:
- template: /eng/common/templates/jobs/jobs.yml
  parameters:
    runAsPublic: ${{ parameters.runAsPublic }}
    enableMicrobuild: true
    enablePublishBuildArtifacts: true
    enablePublishTestResults: true
    enablePublishBuildAssets: true
    enableTelemetry: true
    helixRepo: dotnet/winforms

    jobs:
    - job: Windows_NT
      pool: ${{ parameters.agentPool }}

      variables:

        # needed for signing
        - name: _TeamName
          value: DotNetCore
        - name: _SignType
          value: test
        - name: _SignArgs
          value: ''

        # needed for darc (dependency flow) publishing
        - name: _PublishType
          value: none
        - name: _DotNetPublishToBlobFeed
          value: false
        - name: _PublishArgs
          value: ''
        - name: _OfficialBuildIdArgs
          value: ''

        # needed for helix jobs
        - name: _HelixAgentPool
          value: 'Windows.10.Amd64.Open'
        # - name: _WinformsControlsTestBinDir
        #   value: $(BUILD.SOURCESDIRECTORY)\artifacts\bin\WinformsControlsTest\$(_BuildConfig)\netcoreapp3.0
        # - name: _WinformsFuncTestBinDir
        #   value: $(BUILD.SOURCESDIRECTORY)\artifacts\bin\System.Windows.Forms.Func.Tests\$(_BuildConfig)\netcoreapp3.0
        # - name: _HelixStagingDir
        #   value: $(BUILD.STAGINGDIRECTORY)\helix\functests

        # Override some values if we're building internally
        - ${{ if eq(parameters.runAsPublic, 'false') }}:

          # note: You have to use list syntax here (-name: value) or you will get errors about declaring the same variable multiple times
          - name: _PublishType
            value: blob
          - name: _SignType
            value: real
          - name: _DotNetPublishToBlobFeed
            value: true
          - group: DotNet-Blob-Feed
          - group: DotNet-Symbol-Server-Pats
          - name: _PublishBlobFeedUrl
            value: https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json

          # note: Even though they are referenced here, user defined variables (like $(_SignType)) are not resolved 
          # until the agent is running on the machine. They can be overridden any time before they are resolved,
          # like in the job matrix below (see Build_Debug)
          - name: _SignArgs
            value: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName)
          - name: _PublishArgs
            value: /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1)
              /p:DotNetPublishBlobFeedUrl=$(_PublishBlobFeedUrl)
              /p:DotNetPublishToBlobFeed=$(_DotNetPublishToBlobFeed)
              /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
              /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
          - name: _OfficialBuildIdArgs
            value: /p:OfficialBuildId=$(BUILD.BUILDNUMBER)

          - name: _HelixAgentPool
            value: 'Windows.10.Amd64'

      strategy:
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            # override some variables for debug
            _PublishType: none
            _SignType: test
            _DotNetPublishToBlobFeed : false
          Build_Release:
            _BuildConfig: Release

      steps:
      - checkout: self
        clean: true

      # Use utility script to run script command dependent on agent OS.
      - script: eng\common\cibuild.cmd
          -configuration $(_BuildConfig) 
          -prepareMachine
          $(_PublishArgs)
          $(_SignArgs)
          $(_OfficialBuildIdArgs)
        displayName: Windows Build / Publish

      # # Copy files for helix job
      # - task: CopyFiles@2
      #   inputs:
      #     sourceFolder: $(_WinformsControlsTestBinDir)
      #     contents: '**' 
      #     targetFolder: $(_HelixStagingDir)
      #     cleanTargetFolder: true
      #     #overWrite: false # Optional
      #   displayName: Copy winforms controls tests to helix staging dir
      # - task: CopyFiles@2
      #   inputs:
      #     sourceFolder: $(_WinformsFuncTestBinDir)
      #     contents: '**' 
      #     targetFolder: $(_HelixStagingDir)
      #     overWrite: true
      #   displayName: Copy xUnit func tests to helix staging dir

      - template: /eng/common/templates/steps/helix-publish.yml
        parameters:
          HelixSource: $(_HelixSource)
          HelixType: ̓'tests/functional'
          HelixTargetQueues: $(_HelixAgentPool)
          # secret variable set in Azure DevOps build definition
          # todo: when we go public, get this value from the Helix Anonymous variable group
          # for internal builds, get this value from the DotNet-HelixApi-Access variable group
          HelixAccessToken: $(helix-token) 
          #HelixPreCommands: ''
          #HelixPostCommands: ''
          WorkItemDirectory: #$(_HelixStagingDir)
          WorkItemCommand: #'dotnet.exe exec --depsfile System.Windows.Forms.Func.Tests.deps.json --runtimeconfig System.Windows.Forms.Func.Tests.runtimeconfig.json xunit.console.dll System.Windows.Forms.Func.Tests.dll -noautoreporters -xml System.Windows.Forms.Func.Tests_netcoreapp3.0_x64.xml -html System.Windows.Forms.Func.Tests_netcoreapp3.0_x64.html'
          #CorrelationPayloadDirectory: ''
          XUnitProjects: '$(BUILD.SOURCESDIRECTORY)\src\System.Windows.Forms\tests\UnitTests\System.Windows.Forms.Tests.csproj'
          #XUnitTargetFramework: ''
          #XUnitRunnerVersion: ''
          IncludeDotNetCli: true
          DotNetCliPackageType: 'sdk'
          # We build with '3.0.100-preview-009764' but Helix can't currently use non-publicly-released sdk versions
          # TODO: Move our SDK version up to match this, and remove this line afterwards
          DotNetCliVersion: '3.0.100-preview-009820'
          EnableXUnitReporter: true
          WaitForWorkItemCompletion: true
          condition: succeeded()
          continueOnError: false