// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Drawing;
using System.Reflection;
using Xunit;

namespace System.Windows.Forms.Tests
{
    public class EmbeddedResourceTests : IClassFixture<ThreadExceptionFixture>
    {
        // Get System.Windows.Forms assembly to verify that it contains all the icons that the code uses.
        private readonly Assembly assembly = Assembly.GetAssembly(typeof(AccessibleObject));

        [Theory]
        [InlineData("System.Windows.Forms.Animation")]
        [InlineData("System.Windows.Forms.ActiveDocumentHost")]
        [InlineData("System.Windows.Forms.BindingNavigator")]
        [InlineData("System.Windows.Forms.DataGridViewButtonColumn")]
        [InlineData("System.Windows.Forms.DataGridViewCheckBoxColumn")]
        [InlineData("System.Windows.Forms.DataGridViewComboBoxColumn")]
        [InlineData("System.Windows.Forms.DataGridViewImageColumn")]
        [InlineData("System.Windows.Forms.DataGridViewLinkColumn")]
        [InlineData("System.Windows.Forms.DataGridViewTextBoxColumn")]
        [InlineData("System.Windows.Forms.BindingNavigator.MoveFirst")]
        [InlineData("System.Windows.Forms.BindingNavigator.MoveLast")]
        [InlineData("System.Windows.Forms.BindingNavigator.MovePrevious")]
        [InlineData("System.Windows.Forms.BindingNavigator.MoveNext")]
        [InlineData("System.Windows.Forms.BindingNavigator.AddNew")]
        [InlineData("System.Windows.Forms.BindingNavigator.Delete")]
        [InlineData("System.Windows.Forms.BindingSource")]
        [InlineData("System.Windows.Forms.Button")]
        [InlineData("System.Windows.Forms.CheckBox")]
        [InlineData("System.Windows.Forms.Checked")]
        [InlineData("System.Windows.Forms.CheckedListBox")]
        [InlineData("System.Windows.Forms.ColorDialog")]
        [InlineData("System.Windows.Forms.ComboBox")]
        [InlineData("System.Windows.Forms.ContextMenu")]
        [InlineData("System.Windows.Forms.DataGrid")]
        [InlineData("System.Windows.Forms.DataGridCaption.down")]
        [InlineData("System.Windows.Forms.DataGridCaption.backarrow")]
        [InlineData("System.Windows.Forms.DataGridCaption.backarrow_bidi")]
        [InlineData("System.Windows.Forms.DataGridCaption.Details")]
        [InlineData("System.Windows.Forms.DataGridCaption.right")]
        [InlineData("System.Windows.Forms.DataGridCaption.up")]
        [InlineData("System.Windows.Forms.DataGridRow.right")]
        [InlineData("System.Windows.Forms.DataGridRow.left")]
        [InlineData("System.Windows.Forms.DataGridRow.error")]
        [InlineData("System.Windows.Forms.DataGridRow.star")]
        [InlineData("System.Windows.Forms.DataGridRow.pencil")]
        [InlineData("System.Windows.Forms.DataGridParentRows.LeftArrow")]
        [InlineData("System.Windows.Forms.DataGridParentRows.RightArrow")]
        [InlineData("System.Windows.Forms.DataConnector")]
        [InlineData("System.Windows.Forms.DataNavigator")]
        [InlineData("System.Windows.Forms.DataNavigator.MoveFirst")]
        [InlineData("System.Windows.Forms.DataNavigator.MoveLast")]
        [InlineData("System.Windows.Forms.DataNavigator.MovePrevious")]
        [InlineData("System.Windows.Forms.DataNavigator.MoveNext")]
        [InlineData("System.Windows.Forms.DataNavigator.AddNew")]
        [InlineData("System.Windows.Forms.DataNavigator.Delete")]
        [InlineData("System.Windows.Forms.DateTimePicker")]
        [InlineData("System.Windows.Forms.DefaultControl")]
        [InlineData("System.Windows.Forms.DomainUpDown")]
        [InlineData("System.Windows.Forms.Edit")]
        [InlineData("System.Windows.Forms.TextBox")]
        [InlineData("System.Windows.Forms.MaskedTextBox")]
        [InlineData("System.Windows.Forms.Error")]
        [InlineData("System.Windows.Forms.ErrorProvider")]
        [InlineData("System.Windows.Forms.FlowLayoutPanel")]
        [InlineData("System.Windows.Forms.FolderBrowserDialog")]
        [InlineData("System.Windows.Forms.Form")]
        [InlineData("System.Windows.Forms.FontDialog")]
        [InlineData("System.Windows.Forms.Grid")]
        [InlineData("System.Windows.Forms.DataGridView")]
        [InlineData("System.Windows.Forms.DataGridViewRow.error")]
        [InlineData("System.Windows.Forms.DataGridViewRow.left")]
        [InlineData("System.Windows.Forms.DataGridViewRow.leftstar")]
        [InlineData("System.Windows.Forms.DataGridViewRow.pencil_ltr")]
        [InlineData("System.Windows.Forms.DataGridViewRow.pencil_rtl")]
        [InlineData("System.Windows.Forms.DataGridViewRow.right")]
        [InlineData("System.Windows.Forms.DataGridViewRow.rightstar")]
        [InlineData("System.Windows.Forms.DataGridViewRow.star")]
        [InlineData("System.Windows.Forms.GroupBox")]
        [InlineData("System.Windows.Forms.HelpProvider")]
        [InlineData("System.Windows.Forms.HScrollBar")]
        [InlineData("System.Windows.Forms.HTMLControl")]
        [InlineData("System.Windows.Forms.IndeterminateChecked")]
        [InlineData("System.Windows.Forms.ImageList")]
        [InlineData("System.Windows.Forms.Label")]
        [InlineData("System.Windows.Forms.LinkLabel")]
        [InlineData("System.Windows.Forms.ListBox")]
        [InlineData("System.Windows.Forms.ListView")]
        [InlineData("System.Windows.Forms.MainMenu")]
        [InlineData("System.Windows.Forms.MonthCalendar")]
        [InlineData("System.Windows.Forms.MultiplexPanel")]
        [InlineData("System.Windows.Forms.NotifyIcon")]
        [InlineData("System.Windows.Forms.NumericUpDown")]
        [InlineData("System.Windows.Forms.OpenFileDialog")]
        [InlineData("System.Windows.Forms.Panel")]
        [InlineData("System.Windows.Forms.PictureBox")]
        [InlineData("System.Windows.Forms.PrintPreviewControl")]
        [InlineData("System.Windows.Forms.WebBrowser")]
        [InlineData("System.Windows.Forms.PrintPreviewDialog")]
        [InlineData("System.Windows.Forms.PrintPreviewStrip")]
        [InlineData("System.Windows.Forms.ProgressBar")]
        [InlineData("System.Windows.Forms.RadioButton")]
        [InlineData("System.Windows.Forms.Rebar")]
        [InlineData("System.Windows.Forms.RichEdit")]
        [InlineData("System.Windows.Forms.RichTextBox")]
        [InlineData("System.Windows.Forms.SaveFileDialog")]
        [InlineData("System.Windows.Forms.Splitter")]
        [InlineData("System.Windows.Forms.SplitterPanel")]
        [InlineData("System.Windows.Forms.SplitContainer")]
        [InlineData("System.Windows.Forms.ErrorControl")]
        [InlineData("System.Windows.Forms.TabControl")]
        [InlineData("System.Windows.Forms.TableLayoutPanel")]
        [InlineData("System.Windows.Forms.TabStrip")]
        [InlineData("System.Windows.Forms.TabPage")]
        [InlineData("System.Windows.Forms.ToolBar")]
        [InlineData("System.Windows.Forms.ToolTip")]
        [InlineData("System.Windows.Forms.TrackBar")]
        [InlineData("System.Windows.Forms.TrayIcon")]
        [InlineData("System.Windows.Forms.TreeView")]
        [InlineData("System.Windows.Forms.UserControl")]
        [InlineData("System.Windows.Forms.VScrollBar")]
        [InlineData("System.Windows.Forms.wfc")]
        [InlineData("System.Windows.Forms.Timer")]
        [InlineData("System.Windows.Forms.ComponentModel.OrderImages")]
        [InlineData("System.Windows.Forms.PageSetupDialog")]
        [InlineData("System.Windows.Forms.PrintDialog")]
        [InlineData("System.Windows.Forms.Arrow")]
        [InlineData("System.Windows.Forms.dotdotdot")]
        [InlineData("System.Windows.Forms.Design.EventsTab")]
        [InlineData("System.Windows.Forms.PBAlpha")]
        [InlineData("System.Windows.Forms.PBCategory")]
        [InlineData("System.Windows.Forms.PBEvent")]
        [InlineData("System.Windows.Forms.PBPPage")]
        [InlineData("System.Windows.Forms.PBProp")]
        [InlineData("System.Windows.Forms.PropertyGridInternal.PropertiesTab")]
        [InlineData("System.Windows.Forms.PropertyGrid")]
        [InlineData("System.Windows.Forms.Server.Arrow")]
        [InlineData("System.Windows.Forms.PictureBox.Loading")]
        [InlineData("System.Windows.Forms.IconInError")]
        [InlineData("System.Windows.Forms.ImageInError")]
        [InlineData("System.Windows.Forms.up")]
        [InlineData("System.Windows.Forms.down")]
        [InlineData("System.Windows.Forms.Design.ComponentEditorPage")]
        [InlineData("System.Windows.Forms.ScrollButtonUp")]
        [InlineData("System.Windows.Forms.ScrollButtonDown")]
        [InlineData("System.Windows.Forms.overflowButton")]
        [InlineData("System.Windows.Forms.ToolBarGrip")]
        [InlineData("System.Windows.Forms.ToolStrip")]
        [InlineData("System.Windows.Forms.ToolStripContainer")]
        [InlineData("System.Windows.Forms.ToolStripPanel_standalone")]
        [InlineData("System.Windows.Forms.ToolStripContentPanel")]
        [InlineData("System.Windows.Forms.ToolStripContainer_TopToolStripPanel")]
        [InlineData("System.Windows.Forms.ToolStripContainer_BottomToolStripPanel")]
        [InlineData("System.Windows.Forms.ToolStripContainer_LeftToolStripPanel")]
        [InlineData("System.Windows.Forms.ToolStripContainer_RightToolStripPanel")]
        [InlineData("System.Windows.Forms.MenuStrip")]
        [InlineData("System.Windows.Forms.StatusStrip")]
        [InlineData("System.Windows.Forms.StatusStripPanel")]
        [InlineData("System.Windows.Forms.ToolStripStatusLabel")]
        [InlineData("System.Windows.Forms.ToolStripProgressBar")]
        [InlineData("System.Windows.Forms.ContextMenuStrip")]
        [InlineData("System.Windows.Forms.ToolStripDropDown")]
        [InlineData("System.Windows.Forms.ToolStripButton")]
        [InlineData("System.Windows.Forms.ToolStripLabel")]
        [InlineData("System.Windows.Forms.ToolStripTextBox")]
        [InlineData("System.Windows.Forms.ToolStripComboBox")]
        [InlineData("System.Windows.Forms.ToolStripMenuItem")]
        [InlineData("System.Windows.Forms.ToolStripDropDownMenu")]
        [InlineData("System.Windows.Forms.ToolStripDropDownButton")]
        [InlineData("System.Windows.Forms.ToolStripSplitButton")]
        [InlineData("System.Windows.Forms.ToolStripSeparator")]
        [InlineData("System.Windows.Forms.copy")]
        [InlineData("System.Windows.Forms.cut")]
        [InlineData("System.Windows.Forms.help")]
        [InlineData("System.Windows.Forms.new")]
        [InlineData("System.Windows.Forms.open")]
        [InlineData("System.Windows.Forms.paste")]
        [InlineData("System.Windows.Forms.delete")]
        [InlineData("System.Windows.Forms.viewcode")]
        [InlineData("System.Windows.Forms.properties")]
        [InlineData("System.Windows.Forms.image")]
        [InlineData("System.Windows.Forms.alignment")]
        [InlineData("System.Windows.Forms.displaystyle")]
        [InlineData("System.Windows.Forms.editdropdownlist")]
        [InlineData("System.Windows.Forms.print")]
        [InlineData("System.Windows.Forms.printPreview")]
        [InlineData("System.Windows.Forms.save")]
        [InlineData("System.Windows.Forms.lockControls")]
        [InlineData("System.Windows.Forms.alignToGrid")]
        [InlineData("System.Windows.Forms.bringToFront")]
        [InlineData("System.Windows.Forms.sendToBack")]
        [InlineData("System.Windows.Forms.blank")]
        public void EmbeddedResource_ResourcesExist_Icon(string resourceName)
        {
            using Stream stream = assembly.GetManifestResourceStream(resourceName);
            Assert.NotNull(stream);
            using Icon icon = new(stream);
            Assert.NotNull(icon);
        }

        [Theory]
        [InlineData("System.Windows.Forms.east.cur")]
        [InlineData("System.Windows.Forms.hsplit.cur")]
        [InlineData("System.Windows.Forms.ne.cur")]
        [InlineData("System.Windows.Forms.nomove2d.cur")]
        [InlineData("System.Windows.Forms.nomoveh.cur")]
        [InlineData("System.Windows.Forms.nomovev.cur")]
        [InlineData("System.Windows.Forms.north.cur")]
        [InlineData("System.Windows.Forms.nw.cur")]
        [InlineData("System.Windows.Forms.se.cur")]
        [InlineData("System.Windows.Forms.south.cur")]
        [InlineData("System.Windows.Forms.sw.cur")]
        [InlineData("System.Windows.Forms.vsplit.cur")]
        [InlineData("System.Windows.Forms.west.cur")]
        public void EmbeddedResource_ResourcesExist_Cursor(string resourceName)
        {
            using Stream stream = assembly.GetManifestResourceStream(resourceName);
            Assert.NotNull(stream);
            using Cursor cursor = new(stream);
            Assert.NotNull(cursor);
        }

        [Theory]
        [InlineData("System.Windows.Forms.XPThemes.manifest")]
        public void EmbeddedResource_ResourcesExist_Manifest(string resourceName)
        {
            using Stream stream = assembly.GetManifestResourceStream(resourceName);
            Assert.NotNull(stream);
        }
    }
}
