// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Drawing;
using System.Reflection;
using Xunit;

namespace System.Windows.Forms.Tests
{
    public class EmbeddedResourceTests : IClassFixture<ThreadExceptionFixture>
    {
        // Get System.Windows.Forms assembly to verify that it contains all the resources that the code uses.
        private readonly Assembly assembly = Assembly.GetAssembly(typeof(AccessibleObject));

        [Theory]
        [InlineData("ActiveDocumentHost")]
        [InlineData("alignment")]
        [InlineData("alignToGrid")]
        [InlineData("Animation")]
        [InlineData("Arrow")]
        [InlineData("BindingNavigator")]
        [InlineData("BindingNavigator.AddNew")]
        [InlineData("BindingNavigator.Delete")]
        [InlineData("BindingNavigator.MoveFirst")]
        [InlineData("BindingNavigator.MoveLast")]
        [InlineData("BindingNavigator.MoveNext")]
        [InlineData("BindingNavigator.MovePrevious")]
        [InlineData("BindingSource")]
        [InlineData("blank")]
        [InlineData("bringToFront")]
        [InlineData("Button")]
        [InlineData("CheckBox")]
        [InlineData("Checked")]
        [InlineData("CheckedListBox")]
        [InlineData("ColorDialog")]
        [InlineData("ComboBox")]
        [InlineData("ComponentModel.OrderImages")]
        [InlineData("ContextMenu")]
        [InlineData("ContextMenuStrip")]
        [InlineData("copy")]
        [InlineData("cut")]
        [InlineData("DataConnector")]
        [InlineData("DataGrid")]
        [InlineData("DataGridCaption.backarrow")]
        [InlineData("DataGridCaption.backarrow_bidi")]
        [InlineData("DataGridCaption.Details")]
        [InlineData("DataGridCaption.down")]
        [InlineData("DataGridCaption.right")]
        [InlineData("DataGridCaption.up")]
        [InlineData("DataGridParentRows.LeftArrow")]
        [InlineData("DataGridParentRows.RightArrow")]
        [InlineData("DataGridRow.error")]
        [InlineData("DataGridRow.left")]
        [InlineData("DataGridRow.pencil")]
        [InlineData("DataGridRow.right")]
        [InlineData("DataGridRow.star")]
        [InlineData("DataGridView")]
        [InlineData("DataGridViewButtonColumn")]
        [InlineData("DataGridViewCheckBoxColumn")]
        [InlineData("DataGridViewComboBoxColumn")]
        [InlineData("DataGridViewImageColumn")]
        [InlineData("DataGridViewLinkColumn")]
        [InlineData("DataGridViewRow.error")]
        [InlineData("DataGridViewRow.left")]
        [InlineData("DataGridViewRow.leftstar")]
        [InlineData("DataGridViewRow.pencil_ltr")]
        [InlineData("DataGridViewRow.pencil_rtl")]
        [InlineData("DataGridViewRow.right")]
        [InlineData("DataGridViewRow.rightstar")]
        [InlineData("DataGridViewRow.star")]
        [InlineData("DataGridViewTextBoxColumn")]
        [InlineData("DataNavigator")]
        [InlineData("DataNavigator.AddNew")]
        [InlineData("DataNavigator.Delete")]
        [InlineData("DataNavigator.MoveFirst")]
        [InlineData("DataNavigator.MoveLast")]
        [InlineData("DataNavigator.MoveNext")]
        [InlineData("DataNavigator.MovePrevious")]
        [InlineData("DateTimePicker")]
        [InlineData("DefaultControl")]
        [InlineData("delete")]
        [InlineData("Design.ComponentEditorPage")]
        [InlineData("Design.EventsTab")]
        [InlineData("displaystyle")]
        [InlineData("DomainUpDown")]
        [InlineData("dotdotdot")]
        [InlineData("down")]
        [InlineData("Edit")]
        [InlineData("editdropdownlist")]
        [InlineData("Error")]
        [InlineData("ErrorControl")]
        [InlineData("ErrorProvider")]
        [InlineData("FlowLayoutPanel")]
        [InlineData("FolderBrowserDialog")]
        [InlineData("FontDialog")]
        [InlineData("Form")]
        [InlineData("Grid")]
        [InlineData("GroupBox")]
        [InlineData("help")]
        [InlineData("HelpProvider")]
        [InlineData("HScrollBar")]
        [InlineData("HTMLControl")]
        [InlineData("IconInError")]
        [InlineData("image")]
        [InlineData("ImageInError")]
        [InlineData("ImageList")]
        [InlineData("IndeterminateChecked")]
        [InlineData("Label")]
        [InlineData("LinkLabel")]
        [InlineData("ListBox")]
        [InlineData("ListView")]
        [InlineData("lockControls")]
        [InlineData("MainMenu")]
        [InlineData("MaskedTextBox")]
        [InlineData("MenuStrip")]
        [InlineData("MonthCalendar")]
        [InlineData("MultiplexPanel")]
        [InlineData("new")]
        [InlineData("NotifyIcon")]
        [InlineData("NumericUpDown")]
        [InlineData("open")]
        [InlineData("OpenFileDialog")]
        [InlineData("overflowButton")]
        [InlineData("PageSetupDialog")]
        [InlineData("Panel")]
        [InlineData("paste")]
        [InlineData("PBAlpha")]
        [InlineData("PBCategory")]
        [InlineData("PBEvent")]
        [InlineData("PBPPage")]
        [InlineData("PBProp")]
        [InlineData("PictureBox")]
        [InlineData("PictureBox.Loading")]
        [InlineData("print")]
        [InlineData("PrintDialog")]
        [InlineData("printPreview")]
        [InlineData("PrintPreviewControl")]
        [InlineData("PrintPreviewDialog")]
        [InlineData("PrintPreviewStrip")]
        [InlineData("ProgressBar")]
        [InlineData("properties")]
        [InlineData("PropertyGrid")]
        [InlineData("PropertyGridInternal.PropertiesTab")]
        [InlineData("RadioButton")]
        [InlineData("Rebar")]
        [InlineData("RichEdit")]
        [InlineData("RichTextBox")]
        [InlineData("save")]
        [InlineData("SaveFileDialog")]
        [InlineData("ScrollButtonDown")]
        [InlineData("ScrollButtonUp")]
        [InlineData("sendToBack")]
        [InlineData("Server.Arrow")]
        [InlineData("SplitContainer")]
        [InlineData("Splitter")]
        [InlineData("SplitterPanel")]
        [InlineData("StatusStrip")]
        [InlineData("StatusStripPanel")]
        [InlineData("TabControl")]
        [InlineData("TableLayoutPanel")]
        [InlineData("TabPage")]
        [InlineData("TabStrip")]
        [InlineData("TextBox")]
        [InlineData("Timer")]
        [InlineData("ToolBar")]
        [InlineData("ToolBarGrip")]
        [InlineData("ToolStrip")]
        [InlineData("ToolStripButton")]
        [InlineData("ToolStripComboBox")]
        [InlineData("ToolStripContainer")]
        [InlineData("ToolStripContainer_BottomToolStripPanel")]
        [InlineData("ToolStripContainer_LeftToolStripPanel")]
        [InlineData("ToolStripContainer_RightToolStripPanel")]
        [InlineData("ToolStripContainer_TopToolStripPanel")]
        [InlineData("ToolStripContentPanel")]
        [InlineData("ToolStripDropDown")]
        [InlineData("ToolStripDropDownButton")]
        [InlineData("ToolStripDropDownMenu")]
        [InlineData("ToolStripLabel")]
        [InlineData("ToolStripMenuItem")]
        [InlineData("ToolStripPanel_standalone")]
        [InlineData("ToolStripProgressBar")]
        [InlineData("ToolStripSeparator")]
        [InlineData("ToolStripSplitButton")]
        [InlineData("ToolStripStatusLabel")]
        [InlineData("ToolStripTextBox")]
        [InlineData("ToolTip")]
        [InlineData("TrackBar")]
        [InlineData("TrayIcon")]
        [InlineData("TreeView")]
        [InlineData("up")]
        [InlineData("UserControl")]
        [InlineData("viewcode")]
        [InlineData("VScrollBar")]
        [InlineData("WebBrowser")]
        [InlineData("wfc")]
        public void EmbeddedResource_ResourcesExist_Icon(string resourceName)
        {
            using Stream stream = assembly.GetManifestResourceStream($"System.Windows.Forms.{resourceName}");
            Assert.NotNull(stream);
            using Icon icon = new(stream);
            Assert.NotNull(icon);
        }

        [Theory]
        [InlineData("east.cur")]
        [InlineData("hsplit.cur")]
        [InlineData("ne.cur")]
        [InlineData("nomove2d.cur")]
        [InlineData("nomoveh.cur")]
        [InlineData("nomovev.cur")]
        [InlineData("north.cur")]
        [InlineData("nw.cur")]
        [InlineData("se.cur")]
        [InlineData("south.cur")]
        [InlineData("sw.cur")]
        [InlineData("vsplit.cur")]
        [InlineData("west.cur")]
        public void EmbeddedResource_ResourcesExist_Cursor(string resourceName)
        {
            using Stream stream = assembly.GetManifestResourceStream($"System.Windows.Forms.{resourceName}");
            Assert.NotNull(stream);
            using Cursor cursor = new(stream);
            Assert.NotNull(cursor);
        }

        [Theory]
        [InlineData("System.Windows.Forms.XPThemes.manifest")]
        public void EmbeddedResource_ResourcesExist_Manifest(string resourceName)
        {
            using Stream stream = assembly.GetManifestResourceStream(resourceName);
            Assert.NotNull(stream);
        }
    }
}
