// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Windows.Forms.VisualStyles;

public enum ColorProperty
{
    BorderColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_BORDERCOLOR,
    FillColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_FILLCOLOR,
    TextColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_TEXTCOLOR,
    EdgeLightColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_EDGELIGHTCOLOR,
    EdgeHighlightColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_EDGEHIGHLIGHTCOLOR,
    EdgeShadowColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_EDGESHADOWCOLOR,
    EdgeDarkShadowColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_EDGEDKSHADOWCOLOR,
    EdgeFillColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_EDGEFILLCOLOR,
    TransparentColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_TRANSPARENTCOLOR,
    GradientColor1 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GRADIENTCOLOR1,
    GradientColor2 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GRADIENTCOLOR2,
    GradientColor3 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GRADIENTCOLOR3,
    GradientColor4 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GRADIENTCOLOR4,
    GradientColor5 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GRADIENTCOLOR5,
    ShadowColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_SHADOWCOLOR,
    GlowColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GLOWCOLOR,
    TextBorderColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_TEXTBORDERCOLOR,
    TextShadowColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_TEXTSHADOWCOLOR,
    GlyphTextColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GLYPHTEXTCOLOR,
    GlyphTransparentColor = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GLYPHTRANSPARENTCOLOR,
    FillColorHint = (int)THEME_PROPERTY_SYMBOL_ID.TMT_FILLCOLORHINT,
    BorderColorHint = (int)THEME_PROPERTY_SYMBOL_ID.TMT_BORDERCOLORHINT,
    AccentColorHint = (int)THEME_PROPERTY_SYMBOL_ID.TMT_ACCENTCOLORHINT
}
