// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Windows.Forms.VisualStyles;

public enum IntegerProperty
{
    ImageCount = (int)THEME_PROPERTY_SYMBOL_ID.TMT_IMAGECOUNT,
    AlphaLevel = (int)THEME_PROPERTY_SYMBOL_ID.TMT_ALPHALEVEL,
    BorderSize = (int)THEME_PROPERTY_SYMBOL_ID.TMT_BORDERSIZE,
    RoundCornerWidth = (int)THEME_PROPERTY_SYMBOL_ID.TMT_ROUNDCORNERWIDTH,
    RoundCornerHeight = (int)THEME_PROPERTY_SYMBOL_ID.TMT_ROUNDCORNERHEIGHT,
    GradientRatio1 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GRADIENTRATIO1,
    GradientRatio2 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GRADIENTRATIO2,
    GradientRatio3 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GRADIENTRATIO3,
    GradientRatio4 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GRADIENTRATIO4,
    GradientRatio5 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GRADIENTRATIO5,
    ProgressChunkSize = (int)THEME_PROPERTY_SYMBOL_ID.TMT_PROGRESSCHUNKSIZE,
    ProgressSpaceSize = (int)THEME_PROPERTY_SYMBOL_ID.TMT_PROGRESSSPACESIZE,
    Saturation = (int)THEME_PROPERTY_SYMBOL_ID.TMT_SATURATION,
    TextBorderSize = (int)THEME_PROPERTY_SYMBOL_ID.TMT_TEXTBORDERSIZE,
    AlphaThreshold = (int)THEME_PROPERTY_SYMBOL_ID.TMT_ALPHATHRESHOLD,
    Width = (int)THEME_PROPERTY_SYMBOL_ID.TMT_WIDTH,
    Height = (int)THEME_PROPERTY_SYMBOL_ID.TMT_HEIGHT,
    GlyphIndex = (int)THEME_PROPERTY_SYMBOL_ID.TMT_GLYPHINDEX,
    TrueSizeStretchMark = (int)THEME_PROPERTY_SYMBOL_ID.TMT_TRUESIZESTRETCHMARK,
    MinDpi1 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_MINDPI1,
    MinDpi2 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_MINDPI2,
    MinDpi3 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_MINDPI3,
    MinDpi4 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_MINDPI4,
    MinDpi5 = (int)THEME_PROPERTY_SYMBOL_ID.TMT_MINDPI5,
}
