// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Windows.Forms.IntegrationTests.Common;

public enum MainFormControlsTabOrder
{
    ButtonsButton = 0,
    CalendarButton,
    MultipleControlsButton,
    ComboBoxesButton,
    ComboBoxesWithScrollBarsButton,
    DateTimePickerButton,
    DialogsButton,
    DataGridViewButton,
    DataGridViewInVirtualModeButton,
    TreeViewButton,
    ContentAlignmentButton,
    MenusButton,
    PanelsButton,
    SplitterButton,
    MdiParentButton,
    PropertyGridButton,
    ListViewButton,
    FontNameEditorButton,
    CollectionEditorsButton,
    RichTextBoxesButton,
    PictureBoxesButton,
    FormBorderStylesButton,
    FormShowInTaskbarButton,
    ToggleIconButton,
    ErrorProviderButton,
    TaskDialogButton,
    MessageBoxButton,
    ToolStripsButton,
    TrackBarsButton,
    ScrollBarsButton,
    ToolTipsButton,
    AnchorLayoutButton,
    DockLayoutButton,
    DragAndDrop,
    TextBoxesButton,
    MediaPlayerButton,
    FormOwnerTestButton,
    ListBoxTestButton,
    PasswordButton,
    ChartControlButton,
    ToolStripSeparatorPreferredSize,
    CustomComCtl32Button,
    ScrollableControlsButton
}
