// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.


// This attribute is needed by VS at design-time when enabling the Multilingual App Toolkit
// to localize a project.  Additional assembly attributes are generated by a tool at build-time.
[assembly: System.CLSCompliant(true)]